### ISSUE TITLE
Εγκατάσταση Openfst

### ISSUE THREAD

**Issue by mikatsukons** [slp-ntua/slp-labs#1]
"Μπορείτε να εγκαταστήσετε το Openfst με αυτό το script:
https://github.com/slp-ntua/slp-labs/blob/master/lab1/install_openfst.sh "

Αυτό το script αφορά unix shell ? Αν ναι στο cmd των windows δεν τρέχει ούτε και στο collab που το προσπάθησα,, οπότε μήπως θα μπορούσαμε να έχουμε κάτι πιο συγκεκριμένο? 
Ευχαριστώ

EDIT: αν βάλεις σε όλες τις σειρές (οχι στην 1η) "!" στο collab τρέχει και βγάζει αυτό

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'zlib1g-dev' instead of 'libz-dev'
make is already the newest version (4.1-9.1ubuntu1).
python-dev is already the newest version (2.7.15~rc1-1).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-0ubuntu2).
checkinstall is already the newest version (1.6.2-4ubuntu2).
g++ is already the newest version (4:7.4.0-1ubuntu2.3).
gcc is already the newest version (4:7.4.0-1ubuntu2.3).
wget is already the newest version (1.19.4-1ubuntu2.2).
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
--2020-10-27 10:13:34--  http://www.openfst.org/twiki/pub/FST/FstDownload/openfst-.tar.gz
Resolving www.openfst.org (www.openfst.org)... 206.196.111.47
Connecting to www.openfst.org (www.openfst.org)|206.196.111.47|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-27 10:13:34 ERROR 404: Not Found.

tar: openfst-.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
/bin/bash: line 0: cd: openfst-: No such file or directory
/bin/bash: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.

**Comment by georgepar** [comment]
Αυτό το script τρέχει σε command line σε Linux. Θα πρέπει να βάλετε ένα Ubuntu μηχάνημα ή ένα vm.

**Comment by georgepar** [comment]
Επίσης δουλεύει σε Windows Subsystem for Linux (WSL 2) 
https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by mikatsukons** [comment]
Δηλαδή κάποιος που δεν έχει linux δεν μπορεί να κάνει το εργαστήριο;

**Comment by georgepar** [comment]
Οι πρώτες εργασίες κατά βάση αφορούν linux-based εργαλεία (openfst / kaldi).

Εμείς υποστηρίζουμε τη διαδικασία εγκατάστασης σε linux και μπορούμε να σας βοηθήσουμε με αυτό. 

Αν προτιμάτε εσείς να δουλέψετε σε άλλα λειτουργικά υπάρχουν λύσεις για να μπορέσετε να τα εγκαταστήσετε, αλλά εμείς μπορούμε να σας βοηθήσουμε μόνο σε linux.

**Comment by mikatsukons** [comment]
Κατάλαβα, ευχαριστώ πολύ
