### ISSUE TITLE
[Ερώτημα 8.δ] Άπειρος χρόνος εκτέλεσης της fstcompose

### ISSUE THREAD

**Issue by chrisdim** [slp-ntua/slp-labs#10]
Καλησπέρα,
Η απορία μου σχετίζεται με τη δημιουργία του αυτόματου MLN.binfst με διαδοχική χρήση της fstcompose για όλες τις λέξεις που εμφανίζονται στο αρχείο wiki.txt. Ειδικότερα, με χρήση python έφτιαξα το αυτόματο Μ.binfst που αποδέχεται όλες τις mispelled λέξεις του αρχείου, και το Ν.binfst που αποδέχεται όλες τις σωστές. Όταν πάω να κάνω τη σύνθεση όμως, με χρήση και της fstarcsort, ενώ πετυχαίνει η δημιουργία ML.binfst, στη δημιουργία του MLN.binfst δεν φαίνεται να τερματίζει, μάλλον λόγω του πολύ μεγάλου μεγέθους. Υπάρχει κάποια διαφορετική προσέγγιση ή κάποια εντολή (πχ με κάποιο fstrmepsilon(?)) που να διορθώνει το πρόβλημα;
Σκέφτηκα να το κάνω μεμονωμένα για κάθε λέξη ξεχωριστά και απλώς να αποθηκεύω τα edits στο ίδιο αρχείο, απλώς αυτό νομίζω χρειάζεται κάποιο for loop σε bash script, το οποίο θα ήθελα να αποφύγω.
Ευχαριστώ.

**Comment by chrisdim** [comment]
Αν δεν κάνω λάθος, η προσέγγιση μου είναι μάλλον όλη λάθος γιατί κάνοντας compose ολες τις mispelled με όλες τις σωστές παίρνει καρτεσιανό γινόμενο, δηλαδή 1η λάθος με όλες τις σωστές, 2η λάθος με όλες τις σωστές κλπ, κάτι το οποίο είναι τέρμα λάθος. Οπότε μάλλον πρέπει να τα παίρνω μόνο σε ζευγη;

**Comment by georgepar** [comment]
Ναι αυτή είναι η απάντηση. Ένα ένα σε ζεύγη

**Comment by chrisdim** [comment]
Καλησπέρα,
Κατάφερα να βγάλω τα edits που προκύπτουν για κάθε ζεύγος λέξεων με χρήση μονο python script, ωστόσο χρησιμοποίησα τη βιβλιοθήκη python-Levensthein, και πιο συγκεκριμένα της συνάρτησης editops. Πειράζει που έγινε χρήση έτοιμης βιβλιοθήκης;

**Comment by georgepar** [comment]
Γενικά το να το κάνετε αυτό το βήμα με χρήση αυτομάτων είναι μέρος της άσκησης, και θέλουμε να το κάνετε με χρήση σύνθεσης.
Αν έχετε κολλήσει μπορείτε να προχωρήσετε στα επόμενα, και να γυρίσετε να το φτιάξετε στην πορεία.
