### ISSUE TITLE
lm-build error

### ISSUE THREAD

**Issue by marilena1123** [slp-ntua/slp-labs#120]
Καλημέρα σας, ολοκλήρωσα χωρίς πρόβλημα την εγκατάσταση και τα προηγούμενα βήματα και στο 4.2.2 εμφανίζεται το εξής error: 
LOGFILE:/dev/null
$bin/ngt -i="$inpfile" -n=$order -gooout=y -o="$gzip -c > $tmpdir/ngram.${sdict}.gz" -fd="$tmpdir/$sdict" $dictionary $additional_parameters >> $logfile 2>&1
ls: cannot access 'stat_91004/dict.*': No such file or directory
LOGFILE:/dev/null
$bin/ngt -i="$inpfile" -n=$order -gooout=y -o="$gzip -c > $tmpdir/ngram.${sdict}.gz" -fd="$tmpdir/$sdict" $dictionary $additional_parameters >> $logfile 2>&1
ls: cannot access 'stat_91022/dict.*': No such file or directory
H σύνταξη της εντολής είναι: build-lm.sh -i "./data/local/dict/lm_train.txt" -n 1 -o "./data/local/lm_tmp/lm_phone_ug.ilm.gz"
Σας ευχαριστώ

**Comment by marilena1123** [comment]
Το έτρεξα σύμφωνα με τις οδηγίες εγκατάστασης. Πρέπει να τρέξω και κάτι επιπλέον;

**Comment by georgepar** [comment]
Δοκιμάστε να τρέξετε και το script που έστειλα.

**Comment by marilena1123** [comment]
Καλησπέρα, έτρεξα μόλις το script αλλά δυστυχώς υπάρχει το πρόβλημα

**Comment by anthiv** [comment]
Καλησπέρα, έχει βρεθεί λύση σε αυτό το πρόβλημα;

Αντιμετωπίζουμε ακριβώς το ίδιο.

**Comment by georgepar** [comment]
1. Γράψτε ακριβώς την εντολή που τρεχετε,
2. Βεβαιωθειτε ότι υπάρχουν όλα τα αρχεία που περνάτε σαν ορίσματα σε αυτη την εντολή (ακριβώς με το path το οποίο χρησιμοποιείτε και από το φάκελο μέσα στον οποίο την τρέχετε)
3. Ελέγξτε ότι ο χρήστης σας εχει write permissions στο φάκελο μέσα στον οποίο τρέχετε την εντολή

**Comment by marilena1123** [comment]
Φαίνεται πως παραμένει το θέμα. Μήπως λύθηκε το θέμα;

**Comment by georgepar** [comment]
Τελικά πως το λύσατε;

**Comment by marilena1123** [comment]
Σε εμάς, εκ παραδρομής, το lm αρχείο ήταν txt στο path αντί για text, λόγω της ελάχιστης διαφοράς άργησα να το εντοπίσω. Ζητώ συγγνώμη για την ταλαιπωρία.
