### ISSUE TITLE
[10]

### ISSUE THREAD

**Issue by DimLiak** [slp-ntua/slp-labs#13]
Προσπαθώντας να τρέξω το script run_evaluation.py για την αξιολόγηση πέταγε το εξής error:

![image](https://user-images.githubusercontent.com/63310994/98588579-95688c00-22d4-11eb-87f9-1cac356d7917.png)

Από ότι διαπίστωσα η εντολή "SCRIPT_DIRECTORY = os.path.realpath(__file__)" σου επιστρέφει όλο το path μέχρι να φτάσει στο αρχείο και όχι το path του directory που βρίσκεται το αρχείο, με αποτέλεσμα να μην βρίσκει το path που δίνεται από την εντολή "os.path.join(SCRIPT_DIRECTORY, "../data/spell_test.txt")" στην main. 
Για να τρέχει έκανα την αλλαγή που φαίνεται στην εικόνα:

![image](https://user-images.githubusercontent.com/63310994/98588997-44a56300-22d5-11eb-8617-ff11904118d0.png)

και όντως μετά έτρεξε κανονικά και έβγαλε αποτέλεσμα.

Το πρόβλημα είναι αυτό που ανέλυσα παραπάνω και να αφήσω την αλλαγή ως έχει? ή φταίει κάτι άλλο στον κώδικα μου ή στον τρόπο που το εκτελώ?

**Comment by georgepar** [comment]
Μάλλον φταίει ότι το τρέχεις μέσα από το scripts φακελο. Αν το τρέξεις από το lab1 πρέπει να παίζει

**Comment by DimLiak** [comment]
Δεν κατάλαβα να σας πω την αλήθεια πως μπορώ να το κάνω αυτό που λέτε, βέβαια αφού τα αποτελέσματα τα υπολόγισα με τον παραπάνω τρόπο που περιέγραψα, μπορώ απλά να ξαναλλάξω το αρχείο στο αρχικό έτσι ώστε στον φάκελο που θα παραδώσουμε να είναι έτσι όπως το δίνετε? ή δεν υπάρχει πρόβλημα να το αφήσω και αλλαγμένο?

**Comment by georgepar** [comment]
Εννοώ ότι λογικά έκανες 

```
cd path/to/lab1/scripts
python run_evaluation.py ...
```

Αν κάνεις αυτό

```
cd path/to/lab1
python scripts/run_evaluation.py ...
```

Θα παίξει ως έχει. 
Θα πρότεινα να αφήσεις το σκριπτ στην αρχική του μορφή.

**Comment by DimLiak** [comment]
Το προσπάθησα έτσι όπως λέτε πάλι το ίδιο error πετάει. όπως και να έχει δεν πειράζει, τα αποτελέσματα τα έχω υπολογίσει, οπότε απλά θα φτιάξω το script  στην αρχική του μορφή! Ευχαριστώ !

**Comment by georgepar** [comment]
ok mia xara.
