### ISSUE TITLE
[11]

### ISSUE THREAD

**Issue by DimLiak** [slp-ntua/slp-labs#18]
1) Για το 11α η μέθοδος add-1 smoothing να γίνει στον transducer E? και στην συνέχεια να κάνουμε την σύνθεση με τον V και να συνεχίσουμε έτσι?

2) Για το 11β τα αρχεία που δίνονται είναι για την κατασκευή του αποδοχέα W έτσι ώστε να εκτελέσουμε την σύνθεση με το αυτόματο EV του 11a για να διαπιστώσουμε αλλαγές?

**Comment by georgepar** [comment]
Ναι και ναι

**Comment by DimLiak** [comment]
Το προσπάθησα απλα δεν ταιρίαζουν τα μεγέθη των δύο αυτομάτων όποτε φαντάζομαι πρέπει να φτιάξουμε και νέο V που να κατασκευάζεται από τις 50k λέξεις?

**Comment by georgepar** [comment]
ναι...

**Comment by DimLiak** [comment]
Όπως στο αρχείο wiki.txt υπάρχουν και εδω μη έγκυροι χαρακτήρηρες οπως: é,í και άλλα...
Αυτά να τα διαγράψουμε χειροκίνητα από το αρχείο που χρησιμοποιούμε?

**Comment by georgepar** [comment]
μπορείτε να αγνοησετε τις γραμμές ενώ τις διαβάζετε.

**Comment by DimLiak** [comment]
Ναι ωραία, έτσι το έχω υλοποιησεί. Ευχαριστώ!
