### ISSUE TITLE
Βήμα 3,5

### ISSUE THREAD

**Issue by mikatsukons** [slp-ntua/slp-labs#2]
Καλησπέρα, 
Στο βήμα 3 ο αριθμός καθε λέξης θα αντιστοιχεί σε παράθεση των κωδικών ασκι καθε χαρακτήρα της ή απλά σε εναν αύξοντα αριθμο; 
Στο βήμα 5 για να γραφει η περιγραφή του αυτοματου θα γράψουμε με κώδικα παιθον ένα αρχείο fst που θα προκύψει από το λεξικό που φτιάξαμε στο βήμα 2; 
σαν εισοδο θα παίρνουμε τους κωδικούς ασκι και ως έξοδο θα βγάζουμε <ε> και μόνο στην τελικη κατασταση θα βγάζουμε την έξοδο; 
Ουσιαστικά, δηλαδή, τα αρχεία osyms isyms θα είναι τα αρχεία του βηματος 3 αντίστοιχα;
Γενικά μπορείτε να μας δώσετε κάποιο hint πως γινεται με αλγοριθμικο τρόπο και οχι με το χέρι η αναγνώριση όλων των λέξεων;
Συγγνώμη για τον καταιγισμό ερωτήσεων. 
Ευχαριστώω

**Comment by georgepar** [comment]
> Στο βήμα 3 ο αριθμός καθε λέξης θα αντιστοιχεί σε παράθεση των κωδικών ασκι καθε χαρακτήρα της ή απλά σε εναν αύξοντα αριθμο;

Και τα 2 είναι σωστά. Στο παράδειγμα που δίνουμε τα map-αρει σε ascii, αλλά και με αύξοντα αριθμό θα δουλέψει.

> Στο βήμα 5 για να γραφει η περιγραφή του αυτοματου θα γράψουμε με κώδικα παιθον ένα αρχείο fst που θα προκύψει από το λεξικό που φτιάξαμε στο βήμα 2;

Ναι

> σαν εισοδο θα παίρνουμε τους κωδικούς ασκι και ως έξοδο θα βγάζουμε <ε> και μόνο στην τελικη κατασταση θα βγάζουμε την έξοδο;

Και αυτό μπορεί να γίνει με 2 τρόπους (είτε να έχει input chars / output chars είτε input chars / output words). Για τα επόμενα ερωτήματα μπορεί να βολέψει παραπάνω να βάζεις χαρακτήρες και να βγάζει λέξεις.

> Γενικά μπορείτε να μας δώσετε κάποιο hint πως γινεται με αλγοριθμικο τρόπο και οχι με το χέρι η αναγνώριση όλων των λέξεων;

Για κάθε λέξη στο λεξικό φτιάξε ένα αποδοχέα που να αποδέχεται αυτή τη λέξη. Ένωσε όλους τους αποδοχείς (με ε μετάβαση από κοινή αρχική και προς κοινή τελική κατάσταση.)

**Comment by mikatsukons** [comment]
Τελεια, ευχαριστώ πολύ.
Θεωρείτε καλύτερο layout το αυτοματο να είναι q0->1stletter->2ndletter->...->fs με είσοδο κάθε φορα το αντιστοιχο γράμμα ή 
q0->q1->...->qf με είσοδο και πάλι το κάθε γράμμα. 
Μπορούμε αντίστοιχα με τα isyms, osyms να κωδικοποιήσουμε τις καταστάσεις και αντι για ακεραίους να είναι γράμματα (που μέσω ασκι να γινουν ακεραιοι) ?  **Βεβαια αυτο μπορεί να γίνει μέσα στο script με ord() αλλά εννοώ αν παρέχει τη δυνατότητα η openfst.
Ευχαριστώ και πάλι

**Comment by mikatsukons** [comment]
Μετά από τη σύνταξη των αρχείων όταν εκτελώ την 
fstdeterminize φαινεται να δουλεύει μια χαρά και η fstprint μου δείχνει το dterminized automaton που φαίνεται να είναι σωστό. 
Όταν έπειτα τρέχω την fstminimize ενώ  τρέχει (?) μετά όταν πάω να κάνω print το νέο fst δεν τυπώνεται τιποτα στην οθόνη. 
Αντίστοιχα όταν μετα κανω fstdraw με το determinized+minimized fst τρέχει και παράγεται ενα .dot το οποίο όπως με την εντολή dot -Tpdf V.dot V.pdf  δε φαινεται να παράγει κάποιο αρχείο.  
Από την άλλη αν τρέξω την fstdraw με το determinized automaton  (χωρίς minimization δηλαδη) παράγεται και πάλι ένα .dot αλλά αυτή τη φορά η εντολή dot (...) φαινεται να μην τερματίζει ποτέ. 
Γνωρίζω ότι αυτά που λέω είναι πολύ αόριστα αλλά μήπως υπάρχει κάποιο προφανές bug/προβλημα/βλακεία_που_κάνω ?

**Comment by georgepar** [comment]
Το draw προσπαθείς να το κάνεις σε όλο το λεξικό ή σε ένα μικρό υποσύνολο;
Αν πας να το κάνεις για όλο μιλάμε για ένα fst με 1000αδες καταστάσεις, οπότε λογικό να κρασαρουν όλα.

Φτιάξε ένα acceptor για 5-10 λέξεις και κάνε αυτό draw.

**Comment by mikatsukons** [comment]
Δηλαδη να φτιαξω ενα νέο fst μονο για την οπτικοποιήση; 
Πως μπορώ να εκτυπώσω μονο για 4 5 λέξεις χωρίς να φτιαξω νέο fst?

**Comment by georgepar** [comment]
Αυτό γίνεται με νέο fst. Απλά τρέχεις τον ίδιο κώδικα με μικρό λεξιλόγιο στην είσοδο
