### ISSUE TITLE
Περιγράφη Βήμα 8α

### ISSUE THREAD

**Issue by LoniasGR** [slp-ntua/slp-labs#20]
Καλησπέρα, στο βήμα 8α λέτε να συνθέσουμε τον **αποδοχέα** Μ με τον **μετατροπέα** L και αυτά με τον **μετατροπέα** Ν, Από όσο καταλαβαίνω όμως, ο Ν είναι **αποδοχέας** και όχι μετατροπέας. Έχω καταλάβει κάτι λάθος; 

Επίσης για αυτό το βήμα απλά χρησιμοποιούμε το script που μας έχετε δώσει έτσι; Δεν χρειάζεται να δημιουργήσουμε αυτές τις συναρτήσεις ξανά.

Ευχαριστώ

**Comment by georgepar** [comment]
Ναι ο Ν είναι αποδοχέας.

Και χρησιμοποιείστε τις έτοιμες συναρτήσεις όπου μπορείτε.
