### ISSUE TITLE
13 ανέβασμα tsv

### ISSUE THREAD

**Issue by kagiannis** [slp-ntua/slp-labs#21]
Καλησπέρα,

στη σελίδα του [plotly](https://dash-gallery.plotly.host/dash-word-arithmetic/) δε βλέπω κάπου να λέει ανέβασμα tsv.

Πως τα ανεβάζουμε;

**Comment by georgepar** [comment]
το tsv το ανεβάζετε στο embeddings projector. Στο plotly απλα παίζετε με αυτά που έχει.

**Comment by algorithm314** [comment]
Σωστά έκανα copy λάθος link ευχαριστώ
