### ISSUE TITLE
Προβλημα στην αρχικη εγκατάσταση των πακετων

### ISSUE THREAD

**Issue by a1203-v** [slp-ntua/slp-labs#22]
Ακολουθώντας τα βήματα που είναι ανεβασμένα στο  https://github.com/slp-ntua/python-lab, στις εντολές cp Vagrantfile.slp Vagrantfile vagrant up  δεν εγκαθίστανται όλα τα πακέτα που χρειαζόμαστε. Συγκεκριμένα μας δείχνει αυτό π φαίνεται στην εικόνα.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/65677184/99070046-35196900-25b8-11eb-831d-04fd4219b2e6.png)

**Comment by georgepar** [comment]
Αυτό το script είναι παλιό και δεν το κάνουμε support. Το αφήνουμε απλά βοηθητικά αν κάποιος θέλει να δουλέψει σε VM, αλλά σίγουρα δεν το ζητάμε.

Όπως θα είδατε και εδώ: https://github.com/slp-ntua/slp-labs/issues/1

Μπορούμε να σας υποστηρίξουμε αν δουλεύετε σε ubuntu. Αν είστε σε windows μπορείτε είτε να κάνετε είτε dual boot, είτε να σηκώσετε ένα VM χεράτα. 

Αν δε θέλετετ να κάνετε κάτι από αυτά, υπάρχει και το WSL2, όπου τα περισσότερα εργαλεία πρέπει να παίζουν απροβλημάτιστα, αλλά δεν υπάρχει support από εμάς για αυτό.
