### ISSUE TITLE
Παραδοτέα - Lab1

### ISSUE THREAD

**Issue by DimitriosGkegkas** [slp-ntua/slp-labs#23]
## **Τι χρειάζεται να παραδώσουμε για την 1η εργαστηριακή;** 

- [x] Προφανώς τον **φάκελο scripts** όπου έχουμε υλοποιήσει ότι έλειπε και το **pdf** με την αναφορά. 

- [ ] Τον **φάκελο fsts**, όπως αναφέρετε στο τέλος της εκφώνησης, δεν πρέπει να τον παραδώσουμε.

- [x] Όμως να βάλουμε και τον **φάκελο vocab** με τα αρχεία που έχουμε δημιουργήσει κατά την διάρκεια του εργαστηρίου (_chars.syms, words.syms, words.vocab.txt_); 

- [ ] Ακόμα, το αρχείο **Gutenberg_w2v.100d.model** και ο **φάκελος data** (_edits.txt, embeddings.txt, Gutenberg.txt, metadata.tsv, spell_test.txt, wiki.txt_) πρέπει να παραδοθούν; Καθώς το τελικό .zip αρχείο υπερβαίνει το όριο του moodle. 

- [x] Τέλος, αρκεί η **.html** και **.py** μορφή ενός notebook στο οποίο πραγματοποιούμε τα απαραίτητα βήματα για την εργαστηριακή;  

Ευχαριστώ πολύ

**Comment by georgepar** [comment]
φαίνονται τα ticks?

**Comment by DimitriosGkegkas** [comment]
> φαίνονται τα ticks?

Ναι, ευχαριστώ πολύ
