### ISSUE TITLE
Παραταση Παραδοσης 1ης εργαστηριακης ασκησης;;

### ISSUE THREAD

**Issue by Alphecca-kj** [slp-ntua/slp-labs#24]
Καλησπερα σας,
ηθελα να ρωτησω αν ειναι εφικτο να δοθει μια παραταση για την υποβολη της 1ης εργαστηριακης ασκησης, γιατι τρεχουν πολλες εργασιες παραλληλα και απο αλλα μαθηματα και δεν προλαβαινουμε να την ολοκληρωσουμε.
Σας ευχαριστω!

**Comment by georgepar** [comment]
Η πρώτη εργαστηριακή άσκηση του μαθήματος ολοκληρώθηκε.

Δε θα δωθεί παράταση, αλλά θα αφήσουμε τις υποβολές ανοιχτές για άλλη μια βδομάδα. 
Όποιος δεν προλαβε να παραδώσει μπορεί να παραδώσει μέχρι και την ερχόμενη Δευτέρα (23/11) με penalty 20% στο βαθμό της άσκησης.

Θα βγει και σχετική ανακοίνωση.

**Comment by nox491** [comment]
Με συγχωρείτε, αλλά μέχρι  την Τρίτη δεν είναι η κανονική προθεσμία?

**Comment by georgepar** [comment]
Μέχρι Δευτέρα μεσάνυχτα

**Comment by georgepar** [comment]
Λαθος phrasing στην ανακοίνωση λόγω copy paste. Θα βγάλω ορθή επανάληψη
