### ISSUE TITLE
[Lab 1] Δυνατότητα 2ης Υποβολής

### ISSUE THREAD

**Issue by pmisiakos** [slp-ntua/slp-labs#26]
Καλησπέρα,

Έκανα submit την εργασία μου για το Εργαστήριο 1 και έπειτα συνειδητοποίησα ότι έβαλα για αναφορά αυτήν της προπαρασκευής.
Προσπάθησα να κάνω edit την υποβολή μου και παρόλο που γράφει ότι "this is attempt 1 out of 2" δεν με αφήνει να κάνω δεύτερη υποβολή.

Ήθελα να ρωτήσω γιατί γίνεται αυτό.
Σε περίπτωση που δεν μπορεί να γίνει κάτι για να διορθώσω την υποβολή μου, είναι αρκετό να υποβάλλει ο συνεργάτης μου την σωστή αναφορά;

Παναγιώτης Μισιακός.

**Comment by georgepar** [comment]
Ναι υποβάλλετε μέσω του συνεργάτη και θα το μετρήσουμε. Απλά γράψτε πάνω στην αναφορά που θα υποβάλλετε κάτι του στυλ "Αυτή είναι η σωστή υποβολή".

Επίσης νομίζω μπορείς να κάνεις και withdraw submission.
