### ISSUE TITLE
[Lab 1] Bash Scripting

### ISSUE THREAD

**Issue by the0ch** [slp-ntua/slp-labs#27]
Καλησπέρα! Πως μπορούμε να χρησιμοποιήσουμε bash script σε for loop και να αποθηκεύσουμε το output σε κάποια μεταβλητή ως string;

**Comment by georgepar** [comment]
https://www.cyberciti.biz/faq/bash-for-loop/

κάτι τέτοιο;
Εγώ αντί για μεταβλητή θα έκανα append σε αρχείο και θα τα διάβαζα στο τέλος

**Comment by the0ch** [comment]
ναι αυτο εκανα τελικα, ευχαριστω
