### ISSUE TITLE
προβλημα στη fstrmepsilon

### ISSUE THREAD

**Issue by Alphecca-kj** [slp-ntua/slp-labs#28]
Καλησπερα σας,
στο βημα 5 και στο 6 όπου μας ζηταει να  φτιάξουμε τον αποδοχεα και υστερα να εφαρμοσουμε πανω του τις εντολες fstrmepsilon fstdeterminize fstminimize αντιμετωπιζω προβλημα. Όταν εμφανιζω ενα μικρο αποδοχεα 5 λεξεων η V.fst εμφανιζεται κανονικα, ομως οταν χρησιμοποιω την εντολη fstrmepsilon V.fst Vnew.fst ενω δεν βγαζει κανενα error, οταν το εμφανιζω με την fstdraw δεν ανοιγει καν το αρχειο pdf που προσπαθει να κατεβασει. Γιατι συμβαινει αυτο και πως μπορω να το φτιαξω; 
(επισης σαν epsilon χρησιμοποιω το συμβολο ε και οχι <epsilon>)
Ευχαριστω πολυ!

**Comment by LoniasGR** [comment]
Δεν είμαι βοηθός, αλλά μπορώ να αφήσω την γνώμη μου, και ίσως σε βοηθήσει.

Μπορείς να τσεκάρεις το `.dot` αρχείο για να καταλάβεις τι πήγε στραβά. Λογίκα στην περίπτωση που περιγράφεις, θα είναι κενό (και γιαυτό και το pdf θα σου βγάζει error.  (Τουλάχιστον αυτή ήταν η δική μου εμπειρία so far).  Σχετικά με τον λόγο που συμβαίνει αύτο, δεν το ξέρω αυτό. Μπορείς να τσεκάρεις την [σελίδα](http://www.openfst.org/twiki/bin/view/FST/RmEpsilonDoc) της `fstdraw`, που ίσως σε βοηθήσει κάπου.

> (επισης σαν epsilon χρησιμοποιω το συμβολο ε και οχι )

Δεν κατάλαβα τι εννοείς με αυτό.

**Comment by georgepar** [comment]
Δεν μου έχει προκύψει ποτέ αυτό το πρόβλημα.
Σίγουρα στην rmepsilon είναι το πρόβλημα και όχι στην determinze / minimize?
Το σύμβολο δε θα έπρεπε να έχει σημασία, αλλά δοκίμασε και με <eps> μήπως είναι κάποιο font που δεν παίζει.

Σίγουρα δε νομίζω να είναι θέμα αριθμού καταστάσεων, αφού έχεις 5 λέξεις.

Μήπως το τελικό αυτόματο είναι κενό; Δες το με την fstprint.

Αυτά μπορώ να σκεφτώ.
