### ISSUE TITLE
BHMA 5

### ISSUE THREAD

**Issue by mpektkd** [slp-ntua/slp-labs#3]
Δοκιμαω να δω αν μπορω να ορισω πολλα αυτοματα στο ιδιο αρχειο ωστε να αποφυγω το να φτιαξω πολλα και να τα συνθεσω. Ενω στην αρχη πετυχαινει οταν οαεω να κανω fstremepsilon κλπ μου βγαζει ερρορ. Υπαρει τροπος να ορισουμε πολλα αυτοματα σε ενα αρχειο?

**Comment by georgepar** [comment]
Σε κάθε αρχείο ορίζεται ένα αυτόματο. Δεν χρειάζεται η πράξη της σύνθεσης σε αυτό το ερώτημα.
Δες και αυτή την απάντηση.

**Comment by mpektkd** [comment]
Καλημερα, ναι διαβασα το παραπανω issue. Αυτο που περιγραφετε ειχα σκοπο να κανω αλλα με αυτο τον τροπο θα πρεπει να φτιαξω περιπου 5000 αρχεια και μετα να τα κανω fstunion κι απλα ρωτησα αν θα μπορουσα να τα βαλω ολα σε ενα.

**Comment by georgepar** [comment]
δε χρειάζεται να φτιάξετε 5000 αρχεία ούτε να χρησιμοποιήσετε την fstunion. 
Μπορείτε να το κάνετε όλο με ένα python script που να κάνει append edges σε ένα αρχείο και με καλό χειρισμό του αυξοντα αριθμό των node ids.
