### ISSUE TITLE
Αδυναμία Ανεβάσματος του συμπιεσμένου αρχείου λόγω μεγέθους

### ISSUE THREAD

**Issue by jkalogero** [slp-ntua/slp-labs#31]
Καλησπέρα σας,

Προσπαθώ εδω και μερικά λεπτά να ανεβάσω την αναφορά, ωστόσο τελικά απορρίφθηκε λόγω μεγέθους.
Μπορώ να ξαναυποβάλω χωρίς penalty και ας έχει περάσει η προθεσμία;

**Comment by georgepar** [comment]
Ναι οκ υποβάλλετε μέχρι αύριο με μία σημείωση στην αρχή της αναφοράς.
