### ISSUE TITLE
[Assignment 1] Υποβολή Κώδικα.

### ISSUE THREAD

**Issue by pmisiakos** [slp-ntua/slp-labs#32]
Καλησπέρα,

Συγνώμη που απευθύνω εδώ την ερώτηση μου σχετικά με την αναλυτική άσκηση. Αν γνωρίζετε που πρέπει να ρωτήσω παρακαλώ πείτε το μου. 

Η απορία μου είναι γιατί πρέπει το αρχείο της άσκησης να είναι αποκλειστικά .pdf. Προσωπικά μου φαίνεται λογικό να υποβάλλω και αρχεία κώδικα ώστε να φανεί ο τρόπος με τον οποίο εργάστηκα. (Αναφέρομαι στην υλοποίηση των ασκήσεων 4,5).

Με εκτίμηση,
Παναγιώτης Μισιακός.

**Comment by georgepar** [comment]
θα το αλλάξω σε αρχεία ζιπ

**Comment by georgepar** [comment]
Αν έχετε υποβάλλει ήδη μπορείτε να βάλετε print screens μέσα στο Pdf

**Comment by pmisiakos** [comment]
Ευχαριστώ πολύ!
