### ISSUE TITLE
Γραπτη Εργασια 1 - Ασκηση 7

### ISSUE THREAD

**Issue by nox491** [slp-ntua/slp-labs#33]
Καλησπερα σας,

1)Στην ασκηση 7 αναφερεστε σε Multivariate linear regression ή Univariate? Γενικα υπαρχει καποιος πινακα στο y=Wx+b?
2)Στο 2 ερωτημα τη λυση κλειστου τυπου πρεπει να τη βρουμε για τη συναρτηση κοστους ?

**Comment by georgepar** [comment]
1) όλα είναι πίνακες. Θέλουμε την γενική περίπτωση
2) Η λύση κλειστού τύπου υπολογίζει τις βέλτιστες παραμέτρους Θ = {W, b} που ελαχιστοποιούν τη συνάρτηση κόστους.
