### ISSUE TITLE
Ερώτηση για gcc (Ubuntu 20.04)

### ISSUE THREAD

**Issue by dimitriskranias** [slp-ntua/slp-labs#34]
Καλησπέρα, θα ήθελα να ρωτήσω αν ο οδηγός (του Kaldi) που έχετε για εγκατάσταση του gcc 6 σε Ubuntu 18.04 ισχύει και για Ubuntu 20.04 ή αν πρέπει να ακολουθήσουμε διαφορετική διαδικασία. Επίσης φαίνεται στην τελευταία γραμμή του κώδικα, μετά το gfortran-6 έχει και ένα άλλο ψηφίο αλλά δεν μπορούμε να σύρουμε το slider για να το δούμε. Μήπως μπορείτε να διευκρινίσετε τι γράφει;

**Comment by georgepar** [comment]
Για να βάλεις το gcc-6  μπορείς να δεις εδώ:
https://askubuntu.com/a/1229794

Αν δεν παίζει το zesty θα παίζει το xenial

Επίσης πρέπει να έχει γίνει update το kaldi για να παίζει με πιο νεες version του gcc.

Εκείνη η γραμμή λέει:
sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-6 10

**Comment by dimitriskranias** [comment]
Το βρήκα και γω αυτό το άρθρο, αλλά επειδή δεν μου δούλεψε (ενώ έτρεξα την πρώτη εντολή εξακολουθούσε μετά στο sudo apt install gcc-6 να μου βγάζει ότι δεν το βρίσκει), μου φάνηκε πιο εύκολο εν τέλει να βάλω σε VM τα Ubuntu 16.04. Θα αντιμετωπίσω κάποιο πρόβλημα με αυτή την επιλογή στην άσκηση; (εκτός του performance)

**Comment by georgepar** [comment]
Οχι δεν υπαρχει θέμα.

**Comment by DimLiak** [comment]
Καλησπέρα, έχω δύο ερωτήσεις σχετικές με την εγκατάσταση των πακέτων:

1) Ο υποβιβασμός του gcc απαιτείται μόνο για την εγκατάσταση του Kaldi  ή θα απαιτείται και στην συνέχεια? Δηλαδή μετά την ολοκλήρωση της εγκατάσταση μπορούμε να επαναφέρουμε τον default gcc του συστήματος μας?

2) Στην προσπάθεια μου να εγκαταστήσω το  Kaldi, αφού έκανα downgrade του gcc που προϋπήρχε σε gcc-6, προέκυψαν διάφορα  warnings σαν τα ακόλουθα καθώς έτρεχα τα scripts:

Κατα την εγκατάσταση του IRSTLM:
![Screenshot_3](https://user-images.githubusercontent.com/63310994/101673967-8b1ae880-3a60-11eb-85b8-66f03a18846f.png)

Κατά την εγκατάσταση του OpenBlast:
![Screenshot_4](https://user-images.githubusercontent.com/63310994/101673980-90783300-3a60-11eb-8f6c-f5963a86c68e.png)

Παρόλο αυτού στο τέλος κάθε εγκατάστασης εμφανιζόταν μήνυμα ότι η εγκατάσταση ήταν επιτυχής.
Πρέπει να κάνω κάποια άλλη ενεργεια η ειναι οκ?

**Comment by georgepar** [comment]
Δεν υπάρχει πρόγραμμα σεβαστού μεγέθους που να μην βγάζει warnings στο compilation. Αν το make σου λέει ότι πέτυχε, μια χαρά.

Ο gcc χρειάζεται να γίνει downgrade μόνο για το kaldi.

**Comment by mpektkd** [comment]
στο δευτερο tutorial που δωσατε, παρατηρω οτι δεν περιγραφει τα βηματα για το openBLAS, αυτο θα προκαλεσει προβλημα?...δεν το χρειαζομαστε?

**Comment by mpektkd** [comment]
![image](https://user-images.githubusercontent.com/62422421/101969055-fe705600-3c2a-11eb-9de9-ce1275400f1a.png)
εχω δοκιμασει σχεδον τα παντα και καταληγω συνεχως σε αυτο το σφαλμα, μπορειτε να μου πειτε γτ ή αν μπορω να αντικαταστησω το πακετο openblas με καποιο παρομοιο?...το mkl ειναι παρομοιο?

**Comment by mpektkd** [comment]
μετα απο αρκετο ψαξιμο σε φορουμ κλπ, κατεληξα να μπω στο directory του openblas κα να εκτελεσω τις εξης εντολες:
1.make clean
2.make TARGET = HASWELL
3.sudo make install

μετα απο αυτο ελεγε : OpenBLAS buildin is complete.

και εψαξα στo dierctory /usr/local/ κι βρηκα το αντιστοιχο αρχειο .so
αλλα οταν εκτελουσα την εντολη ./configure ....κλπ, δεν το αναγνωριζε καθως δεν υπηρχε αρχειο install στο kaldi/tools/OpenBLAS 
Ετσι ετρεξα ./configure χωρις flags, καιφανηκε να πετυχαινει χρησιμοποιωντας την βιβλιοθηκη MKL.

Η ερωτηση μου ειναι, θα υπαρξει καποιο προβλημα στο μελλον?
