### ISSUE TITLE
[Lab 2][Προεργασία] Μετασχηματισμοί Προτάσεων

### ISSUE THREAD

**Issue by danaibrilli** [slp-ntua/slp-labs#36]
Καλησπέρα!
Θα ήθελα να ρωτήσω σχετικά με το τελευταίο βήμα της προεργασίας. Κατά την αντικατάσταση των λέξεων κάθε πρότασης στην αντίστοιχη αλληλουχία φωνημάτων, τι πρέπει να κάνουμε όταν μία λέξη αντιστοιχίζεται σε παραπάνω από μία αλληλουχίες? Χρησιμοποιούμε όλους τους πιθανούς τρόπους γραφής ή επιλέγουμε έναν από αυτούς ?

Ευχαριστώ πολύ!

**Comment by efthymisgeo** [comment]
επιλέξτε έναν
