### ISSUE TITLE
[Lab 2] mfcc.conf

### ISSUE THREAD

**Issue by mikatsukons** [slp-ntua/slp-labs#37]
" 4. Δημιουργείστε το φάκελο conf και μέσα σε αυτόν αντιγράψτε το αρχείο mfcc.conf που σας δώθηκε στις διευκρινίσεις. " 
Σε ποιές διευκρινίσεις αναφέρεστε;

**Comment by efthymisgeo** [comment]
https://github.com/slp-ntua/slp-labs/blob/master/lab2/mfcc.conf
