### ISSUE TITLE
[Lab 2][Step 4.2]

### ISSUE THREAD

**Issue by mikatsukons** [slp-ntua/slp-labs#38]
"1. Μέσα στο φάκελο data/local/dict θα αποθηκεύσετε τα βασικά αρχεία που θα χρησιμεύσουν για τη δημιουργία του
γλωσσικού μοντέλου."
....
" Δημιουργείστε το αρχείο lm_train.text προσθέτοντας στο αρχείο text που δημιουργήσατε στην προπαρασκευή
τις ειδικές μονάδες <s> και </s> στην αρχή και στο τέλος της κάθε πρότασης αντίστοιχα. 3 τέτοια αρχεία
πρέπει να δημιουργηθούν, ένα για κάθε σετ. "

εφόσον τα αρχεία που δημιουργούμε στο 4.2.1 βρίσκονται όλα στο ίδιο directory και θέλετε να φτιάξουμε 3 αρχεία (train dev test) lm_train.text αυτά δεν γίνεται να έχουν το ίδιο ονομα προφανώς. Τα ονομάζουμε όπως θέλουμε; ή εννοείτε το καθε lm_train.text να το δημιουργήσουμε εντός του αντίστοιχου φακέλου train, dev, test?

**Comment by mikatsukons** [comment]
Επίσης δεν καταλαβαίνω, τι νόημα έχει να δημιουργήσουμε γλωσσικό μοντέλο για τα test data μας; δεν υποτιθεται οτι ειναι "άγνωστα" σε εμάς μέχρι το evaluation?
++ Το ίδιο ερώτημα παραμένει και στο επόμενο ερώτημα με τα "<αρχείο_εξόδου.ilm.gz>" που δημιουργεί το build-lm.sh

**Comment by georgepar** [comment]
> εφόσον τα αρχεία που δημιουργούμε στο 4.2.1 βρίσκονται όλα στο ίδιο directory και θέλετε να φτιάξουμε 3 αρχεία (train dev test) lm_train.text αυτά δεν γίνεται να έχουν το ίδιο ονομα προφανώς. Τα ονομάζουμε όπως θέλουμε; ή εννοείτε το καθε lm_train.text να το δημιουργήσουμε εντός του αντίστοιχου φακέλου train, dev, test?

Οχι στο data/local/dict μπορείτε να βάλετε τα lm_train.text, lm_dev.text, lm_test.text

> Επίσης δεν καταλαβαίνω, τι νόημα έχει να δημιουργήσουμε γλωσσικό μοντέλο για τα test data μας; δεν υποτιθεται οτι ειναι "άγνωστα" σε εμάς μέχρι το evaluation?

Δίκιο έχεις. Αν δεν κάνω λάθος τελικά μόνο τo lm από τα train χρησιμοποιεί.

> ++ Το ίδιο ερώτημα παραμένει και στο επόμενο ερώτημα με τα "<αρχείο_εξόδου.ilm.gz>" που δημιουργεί το build-lm.sh

build-lm.sh <some-args> train_lm.ilm.gz η κάτι τέτοιο. Όπου περιμένουμε συγκεκριμένη ονομασία το λέμε στην εκφώνηση.
