### ISSUE TITLE
[Lab 2][4.2.1]

### ISSUE THREAD

**Issue by DimLiak** [slp-ntua/slp-labs#40]
Καλησπέρα, 
Στην προσπάθεια δημιουργίας του αρχείου "nonsilence_pnones.txt", εργάστηκα με αρχικό αρχείο το lexicon.txt που ήταν ένα από τα αρχεία που κατεβάσαμε από το drive στην προπαρασκευή και έβγαλα από εκεί τα Phones. Ωστόσο όταν τελείωσα παρατήρησα τα εξής:
1) Προκύπτουν 41 φωνήματα και όχι 44 όπου είναι τα φωνήματα της αγγλικής (https://www.dyslexia-reading-well.com/44-phonemes-in-english.html)
2) Μέσα σε αυτά υπάρχει το φώνημα <oov> που στο lexicon.txt αντιστοιχεί στην λέξη <oov>, και η αλήθεια είναι ότι δεν μου βγάζει λογική γιατί να υπάρχει τέτοια λέξη στο λεξικό 
3) Τέλος στο lexicon.txt υπάρχει η λέξη SIL που αντιστοιχεί στο φώνημα sil, που εν μέρει το sil δεν είναι φώνημα λέξης και από την άλλη θα βρίσκεται σε σύγκρουση με το άφωνο sil

Οπότε τι να κάνω με όλα τα παραπάνω, μήπως τα φωνήματα μπορώ να τα πάρω κατευθείαν από κάποια βιβλιοθήκη για να μην υπάρχουν όλα τα παραπάνω θέματα?

**Comment by georgepar** [comment]
> Προκύπτουν 41 φωνήματα και όχι 44 όπου είναι τα φωνήματα της αγγλικής (https://www.dyslexia-reading-well.com/44-phonemes-in-english.html)

Ισχύει αλλά για τις ανάγκες του εργαστηρίου είναι good enough. Αν θες μπορείς να χρησιμοποιήσεις κάποιο πιο πλήρες λεξικό, αλλά εμείς υποστηρίζουμε αυτό που έχουμε δώσει

> Μέσα σε αυτά υπάρχει το φώνημα που στο lexicon.txt αντιστοιχεί στην λέξη , και η αλήθεια είναι ότι δεν μου βγάζει λογική γιατί να υπάρχει τέτοια λέξη στο λεξικό

Ποια λέξη; εννοείς το κόμμα;

> Τέλος στο lexicon.txt υπάρχει η λέξη SIL που αντιστοιχεί στο φώνημα sil, που εν μέρει το sil δεν είναι φώνημα λέξης και από την άλλη θα βρίσκεται σε σύγκρουση με το άφωνο sil

Αυτό απαιτείται από το kaldi, όπου το silence το διαχειρίζεται ως φώνημα.

**Comment by DimLiak** [comment]
Στο δεύτερο ερώτημα είναι το φώνημα 'οοv' μέσα σε '<' kai '>' , απλά όταν το έγραψα όλο μαζί μάλλον δεν εμφανίστηκε στο παραπάνω κείμενο. Με αυτό τι κάνω?

**Comment by DimLiak** [comment]
να αφαιρέσω τα '<' και '>' και να το προσθέσω στα φωνήματα ή να το αγνοήσω?

**Comment by georgepar** [comment]
οχι το <oov> σημαίνει out of vocabulary. είναι δεσμευμένο για περιπτώσεις που δεν αναγνωρίζεται εγκυρη λέξη. Το αφήνεις ως έχει και το χρησιμοποιείς κατά τη δημιουργία του γλωσσικού μοντέλου.

**Comment by DimLiak** [comment]
Τέλεια! Ευχαριστώ πολύ!
