### ISSUE TITLE
[Lab 2] [4.2.2]

### ISSUE THREAD

**Issue by DimLiak** [slp-ntua/slp-labs#42]
Προσπαθώ να εκτελέσω την εντολή:
build-lm.sh -i <αρχείο lm_train.text> -n <τάξη γλωσσικού μοντέλου> -o <αρχείο_εξόδου.ilm.gz>
ωστόσο συνεχίζει να μου βγαίνει το εξής:
Set IRSTLM environment variable with path to irstlm
όπου έψαξα online για το πώς μπορώ να το επιλύσω αλλά δεν ήταν αποτελεσματικά όσα βρήκα 
Έχετε να μου προτείνεται τι να κάνω για να το επιλύσω?

**Comment by georgepar** [comment]
Πρέπει να τρέξεις το `tools/extras/install_irstlm.sh` για να εγκαταστήσεις το εργαλείο και μετά να κάνεις `source path.sh` και πρέπει να παίξει
