### ISSUE TITLE
[Lab 2] [Step 4.1] timit

### ISSUE THREAD

**Issue by mikatsukons** [slp-ntua/slp-labs#43]
Οταν τρέχω το timit_format_data παίρνω αυτό

WARNING (arpa2fst[5.5.855\~1-c013e]:ConsumeNGram():arpa-lm-compiler.cc:313) line 53 [-3.16815    \<s\> \<s\>] skipped: n-gram has invalid BOS/EOS placement
WARNING (arpa2fst[5.5.855\~1-c013e]:Read():arpa-file-parser.cc:219) line 54 [-3.13185    \<s\> utterance_id_456] skipped: word 'utterance_id_456' not in symbol table

ενώ το αρχείο μου lm_train.text εχει αυτη τη μορφη
utterance_id_456 \<s\> sil dh ih s w ao z iy z iy f r er ah s  \<\s\>
utterance_id_456 \<s\> sil jh ey n m ey er n m ao r m ah n iy b ay w er k ih ng hh aa r d  \<\s\>
utterance_id_456 \<s\> sil sh iy ih z th ih n er dh ae n ay ae m  \<\s\>

Επίσης παίρνω αυτά τα errors:
Preparing language models for test
utils/validate_data_dir.sh: file ./train/utt2spk is not sorted or has duplicates
utils/validate_data_dir.sh: file ./dev/utt2spk is not sorted or has duplicates
utils/validate_data_dir.sh: file ./test/utt2spk is not sorted or has duplicates

Ενώ το sortαρισμα το κάνω έτσι:

mihaelakonstantinou@mikatsusmachine:\~/kaldi/egs/usc/data/train$sort wav.scp -o wav.scp
mihaelakonstantinou@mikatsusmachine:\~/kaldi/egs/usc/data/train$sort utt2spk -o utt2spk

και τα αρχεία σορταρισμένα έχουν αυτή τη μορφή:

utterance_id_001 f1
utterance_id_001 f5
utterance_id_001 m1
utterance_id_001 m3
utterance_id_002 f1
utterance_id_002 f5
utterance_id_002 m3
utterance_id_003 f1
utterance_id_003 f5
utterance_id_003 m1

μήπως τα θέλουμε sortαρισμένα ως προς κάτι άλλο ; η μορφή που δίνεται απ την εκφώνηση πάντως αν δεν κάνω λάθος σε αυτήν την ταξινόμηση οδηγεί

**Comment by mikatsukons** [comment]
η build-lm.sh θα πρέπει να τρεχτεί μόνο για το lm_train.text σωστα; ειδάλλως τα μοντέλα αρπα που θα προκύψουν για dev και test θα έχουν κονφλικτ στο όνομα. Ρωτάω γιατι ακολουθώ και πάλι τα βήματα να δω τι δεν κάνω σωστά

**Comment by georgepar** [comment]
> μήπως τα θέλουμε sortαρισμένα ως προς κάτι άλλο ; η μορφή που δίνεται απ την εκφώνηση πάντως αν δεν κάνω λάθος σε αυτήν την ταξινόμηση οδηγεί

Αν φτιάξεις τα labels όπως είχαμε αναφέρει στο εργαστήριο στη μορφή `<speaker>_utterance_<utterance_id>` (πχ `m3-utterance-1468` πρέπει να παίξει απροβλημάτιστα. Τα samples πρέπει να είναι sorted ως προς speaker και utterance.

**Comment by mikatsukons** [comment]
Γενικά ωστόσο αυτό είναι bug της εκφώνησης γιατί σε άλλη μορφή λέει να γίνουν τα αρχία, ίσως να διορθωνόταν ή να εφευγε το sort γιατι ουτως ή αλλως τα δεδομένα δίνονται sorted ως προς τους speakers και τα utterances. Πάντως ένα από τα δύο πρέπει να διορθωθεί.

**Comment by mikatsukons** [comment]
Θα μπορούσατε να μου απαντήσετε διότι δεν θα προλαβαίνουμε την προθεσμία; ίσως βοηθούσε να μας δείχνατε τμηματα των δικών σας αρχείων (5 πρωτες γραμμες ξερωγω) να μπορούμε να δούμε που έχουμε λαθη γιατί το debugging σε αυτούς τους κώδικες με τοσα αρχεία και τόσες παραμέτρους που δεν ξέρουμε πως θα επρεπε να είναι δεν είναι ιδιαίτερα εφικτό.

**Comment by DimLiak** [comment]
Καλησπέρα, 
Βρίσκομαι και εγώ σε αυτό το σημείο και αντιμέτωπίζω το ίδιο ακριβώς πρόβλημα.
Ονόμασα τα labels με την μορφή που αναφερέται στο παραπάνω σχόλιο αλλά και πάλι δεν φαίνεται να τρέχει .

Για εποπτέια παραθέτω μερικές γραμμές από το αρχείο  lm_train.txt μήπως υπάρχει κάποιο θέμα στην αναπαράσταση:

f1_utterance_001 <s> sil dh ih s w ao z iy z iy f r er ah s sil <\s>
f1_utterance_002 <s> sil jh ey n m ey er n m ao r m ah n iy b ay w er k ih ng hh aa r d sil <\s>
f1_utterance_003 <s> sil sh iy ih z th ih n er dh ae n ay ae m sil <\s>
f1_utterance_005 <s> sil n ah th ih ng ih z ae z ah f eh n s ih v ae z ih n ah s ah n s sil <\s>
f1_utterance_006 <s> sil w ay y eh l ao r w er iy ow v er s ih l iy ay t ah m z sil <\s>
f1_utterance_007 <s> sil w eh r w er y uw w ay l w iy w er ah w ey sil <\s>
f1_utterance_008 <s> sil aa r y ao r g r ey d z hh ay er ao r l ow er dh ae n n ae n s iy z sil <\s>

Επίσης τα warnings και κατ' επέκταση το error ποτ βγάζει έιναι τα καόλουθα:

WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 7 [-4.43838	f1_utterance_001] skipped: word 'f1_utterance_001' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 21 [-1.57239	<\s>] skipped: word '<\s>' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 22 [-4.43838	f1_utterance_002] skipped: word 'f1_utterance_002' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 34 [-4.43838	f1_utterance_003] skipped: word 'f1_utterance_003' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 38 [-4.43838	f1_utterance_005] skipped: word 'f1_utterance_005' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 41 [-4.43838	f1_utterance_006] skipped: word 'f1_utterance_006' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 46 [-4.43838	f1_utterance_007] skipped: word 'f1_utterance_007' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 48 [-4.43838	f1_utterance_008] skipped: word 'f1_utterance_008' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 50 [-4.43838	f1_utterance_009] skipped: word 'f1_utterance_009' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 52 [-4.43838	f1_utterance_010] skipped: word 'f1_utterance_010' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 53 [-4.43838	f1_utterance_011] skipped: word 'f1_utterance_011' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 54 [-4.43838	f1_utterance_012] skipped: word 'f1_utterance_012' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 55 [-4.43838	f1_utterance_013] skipped: word 'f1_utterance_013' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 56 [-4.43838	f1_utterance_014] skipped: word 'f1_utterance_014' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 57 [-4.43838	f1_utterance_015] skipped: word 'f1_utterance_015' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 58 [-4.43838	f1_utterance_017] skipped: word 'f1_utterance_017' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 60 [-4.43838	f1_utterance_018] skipped: word 'f1_utterance_018' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 61 [-4.43838	f1_utterance_019] skipped: word 'f1_utterance_019' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 62 [-4.43838	f1_utterance_020] skipped: word 'f1_utterance_020' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 63 [-4.43838	f1_utterance_022] skipped: word 'f1_utterance_022' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 64 [-4.43838	f1_utterance_023] skipped: word 'f1_utterance_023' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 66 [-4.43838	f1_utterance_024] skipped: word 'f1_utterance_024' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 67 [-4.43838	f1_utterance_025] skipped: word 'f1_utterance_025' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 68 [-4.43838	f1_utterance_026] skipped: word 'f1_utterance_026' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 70 [-4.43838	f1_utterance_027] skipped: word 'f1_utterance_027' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 71 [-4.43838	f1_utterance_029] skipped: word 'f1_utterance_029' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 72 [-4.43838	f1_utterance_030] skipped: word 'f1_utterance_030' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 73 [-4.43838	f1_utterance_032] skipped: word 'f1_utterance_032' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 74 [-4.43838	f1_utterance_033] skipped: word 'f1_utterance_033' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:219) line 75 [-4.43838	f1_utterance_034] skipped: word 'f1_utterance_034' not in symbol table
WARNING (arpa2fst[5.5.863~1-813b7]:Read():arpa-file-parser.cc:259) Of 1469 parse warnings, 30 were reported. Run program with --max-arpa-warnings=-1 to see all warnings
LOG (arpa2fst[5.5.863~1-813b7]:RemoveRedundantStates():arpa-lm-compiler.cc:359) Reduced num-states from 1 to 0
ERROR (arpa2fst[5.5.863~1-813b7]:Check():arpa-lm-compiler.cc:365) Arpa file did not contain the beginning-of-sentence symbol <s>.

Υπάρχει κάποιος τρόπος για να λήθει αυτό?

**Comment by DimLiak** [comment]
UPDATE!
Μέτα από δίαφορεσ διαδικασίες κατάφερα να το τρέξω και να παράξω τα G.fst ωστόσο συνεχίζω να παίρνω καποια warnings που σχετίζονται με τα labels:
![Screenshot from 2020-12-28 03-53-43](https://user-images.githubusercontent.com/63310994/103184402-bc990e00-48c0-11eb-9350-a35dd0ca1e0c.png)
Από την στιγμή που δημιουργείται το fst τα warnings πρέπει να με προβληματίζουν ή δεν υπάρχει θέμα?

**Comment by georgepar** [comment]
Ναι μια χαρά είναι. Αν θες να διώξεις τα warnings μπορείς να βγάλεις την πρώτη στήλη:

```
f1-utterance-001 <s> sil dh ih s w ao z iy z iy f r er ah s sil </s>
-> 
<s> sil dh ih s w ao z iy z iy f r er ah s sil </s>
```

αλλά και έτσι θα παίξει μια χαρά.
