### ISSUE TITLE
[Lab2] [4.2.4]

### ISSUE THREAD

**Issue by christinetkn** [slp-ntua/slp-labs#44]
Καλησπέρα σας και χρόνια πολλά!
Στο συγκεκριμένο βήμα, κάνοντας "source path.sh" και τρέχοντας την εντολή "utils/prepare_lang.sh data/local/dict '' data/local/lang data/lang" κάθε έλεγχος τερματιζόταν με  το μήνυμα "ΟΚ", μέχρι που φτάνουμε στον έλεγχο "Checking word-level disambiguation symbols..." όπου λαμβάνουμε "sh: 1: export: (x86)/NVIDIA: bad variable name" και στη συνέχεια --> ERROR: number of reconstructed words 0 does not match real number of words 69

Συγκεκριμένα:

Checking word-level disambiguation symbols...
--> data/lang/phones/wdisambig.txt exists (newer prepare_lang.sh)
Checking word_boundary.int and disambig.int
**sh: 1: export: (x86)/NVIDIA: bad variable name**
--> generating a 69 word/subword sequence
sh: 1: export: (x86)/NVIDIA: bad variable name
**--> ERROR: number of reconstructed words 0 does not match real number of words 69; indicates problem in L.fst or word_boundary.int.  phoneseq = , wordseq = n th w b s hh uw ay ah ao v iy dh uh <oov> k p er ey d p n ng z dh p ng ow iy t eh er w g b jh sil p z aw p ow iy ih ch d p eh er d zh dh sil z jh ch oy n b s uw uw m ey ah ch eh ay dh**
--> generating a 87 word/subword sequence
sh: 1: export: (x86)/NVIDIA: bad variable name

Checking data/lang/oov.{txt, int} ...
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> 1 entry/entries in data/lang/oov.txt
--> data/lang/oov.int corresponds to data/lang/oov.txt
--> data/lang/oov.{txt, int} are OK

**sh: 1: export: (x86)/NVIDIA: bad variable name
--> ERROR: data/lang/L.fst is not olabel sorted
sh: 1: export: (x86)/NVIDIA: bad variable name
--> ERROR: data/lang/L_disambig.fst is not olabel sorted
--> ERROR (see error messages above)
prepare_lang.sh: error validating output**

Έπειτα, με την εντολή "echo $PATH" παρατηρήσαμε ότι μεταξύ άλλων εμφανίζεται το path :
.../mnt/c/**Program Files (x86)/NVIDIA Corporation/**PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA ...

σκεφτήκαμε ότι ενδεχομένως να ενοχλεί το πρόγραμμά μας τα κενά που υπάρχουν μεταξύ των λέξεων "Program Files (x86)" και λόγω αυτού να οδηγούμαστε στα errors.

Τέλος, δεν είχαμε καταφέρει να κατεβάσουμε το openblas σύμφωνα με την εντολή 
"./configure --shared --openblas-root=../tools/OpenBLAS/install", το αναφέρω επειδή δεν γνωρίζω αν παίζει ρόλο.

Ευχαριστώ πολύ για το χρόνο σας!

**Comment by georgepar** [comment]
Όπως έχουμε ξαναπεί, δεν μπορούμε να σας παρέχουμε βοήθεια αν δεν δουλεύετε σε linux. Εγώ θα έλεγα απενεργοποιείστε ότι έχει να κάνει με GPU, καθώς δεν το χρειάζεστε για το Kaldi, αλλά δεν είμαι σίγουρος πώς θα το κάνετε να παίξει σε windows.
