### ISSUE TITLE
[Lab 2] [4.2.4]

### ISSUE THREAD

**Issue by DimLiak** [slp-ntua/slp-labs#45]
Καλές γιορτές!
Προσπαθώ να κάνω το 4 βήμα του 4.2 ωστόσο αντιμετωπίζω κάποια προβλήματα.
Tρέχοντας την εντολή χωρίς ορίσματα για να δω το usage έβγαζε το εξής μήνυμα:
Usage: utils/prepare_lang.sh "dict-src-dir" "oov-dict-entry" "tmp-dir" "lang-dir"
από αυτά δεν έχω καταλάβει ακριβώς σε ποιο directory αναφέρεται το όρισμα "tmp-dir".

**Comment by DimLiak** [comment]
Εν τέλει έβαλα ένα τυχαίο όνομα κενού directory και άρχισε να τρέχει ομως μου έβγαλε το εξής error:
![image](https://user-images.githubusercontent.com/63310994/103160372-f42e8a00-47dc-11eb-9b6c-41a8429165a8.png)
που βασικά μου λέει για το σορτάρισμα των olabels. Από την προηγούμενη εργαστηριακή θυμάμαι πώς υπάρχει εντολή για να κάνουμε το sort εμείς αλλά λογικά δεν θα έπρεπε να τα σορτάρει από μόνο του το πρόγραμμα και να μην σκάει?
Η μήπως έχει να κάνει με το directory που έδωσα στο όρισμα, που αναφέρω παραπάνω, και ήθελε κάποιο συγκεκριμένο?

**Comment by georgepar** [comment]
dict directory -> `data/local/dict`
oov entry -> `"<oov>"`  Το token.μέσα σε αυτάκια. όχι ένα αρχείο που περιεχει το token. 
tmp directory -> φτιάξε ένα random directory για temp αρχεία.
