### ISSUE TITLE
[Lab 2] [4.2] perplexity

### ISSUE THREAD

**Issue by DimLiak** [slp-ntua/slp-labs#46]
Καλησπέρα,
Στο τέλος του βήματος 4.2 ζητείται ο υπολογισμός του perplexity για το validation και το test set. Ωστόσο δεν δίνονται περαιτέρω διευκρινήσεις. Ο υπολογισμός θα γίνεται μέσω script που θα δημιουργήσουμε εμείς και αν ναι τότε να θεωρήσουμε την προσέγγιση bigram ή υπάρχει έτοιμο αρχείο στο kaldi για τον υπολογισμό?

**Comment by georgepar** [comment]
https://github.com/slp-ntua/slp-labs/issues/47
