### ISSUE TITLE
[4.5.1]

### ISSUE THREAD

**Issue by DimLiak** [slp-ntua/slp-labs#49]
1. Εξάγετε τα triphone alignments για τα train, validation και test sets.
Σε αυτό το ερώτημα θέλετε να κανουμε την διαδικασία του 4.4.5 για όλα τα sets? Επίσης ποια η λογική να επεξεργαστούμε το test set αφού ουσιαστικά ο ελέγχος πρέπει να γίνει πάνω σε αυτό?

**Comment by georgepar** [comment]
το δίκτυο θα εκπαιδευτεί στο train και θα γίνει validate στο dev. 
Το test set το χρησιμοποιείτε μόνο για να κάνετε predict τα posteriors (`extract_posteriors.py`), τα οποία χρειάζονται για την πρόβλεψη.

Σε αυτό το μέρος αντικαθιστάτε τον υπολογισμό της πιθανότητας κάθε frame από ένα GMM με ένα DNN. Το alignment κτλ είναι απλά τα  κομμάτια που χρειάζονται για να κάνετε την τελική πρόβλεψη πάνω στο test set.

**Comment by mpektkd** [comment]
το alignment για τα triphones σαυτο το βημα εχουν σχεση με το 4.4.5?

**Comment by georgepar** [comment]
Σε κάθε βήμα εκπαιδεύετε ένα πιο πολύπλοκο μοντέλο που βασίζεται στο μοντέλο που έχετε εκπαιδεύσει στο προηγούμενο.
Τα δεδομένα σας δίνονται unaligned (δηλαδή κάποια δευτερόλεπτα ομιλίας και το transcription που αντιστοιχεί σε αυτά, χωρίς timestamps για το ποιο φώνημα εμφανίζεται ποια χρονική στιγμή). Το alignment είναι η διαδικασία όπου εξάγεις αυτά τα timestamps.

Έτσι στην αρχή (4.4.1) εκπαιδεύετε ένα χοντροκομμένο monophone μοντέλο, το οποίο κάνει κάποια iterations:

```
1. M = train monophone model
2. align data using M
3.  go to 1. 
```

Στο τέλος αυτής της διαδικασίας έχετε ένα αξιοπρεπές μονοφωνικό μοντέλο το οποίο το χρησιμοποιείτε στο βήμα 4.4.5 για να παράξετε τα alignments που θα χρησιμοποιηθούν για την εκπαίδευση του triphone.

Στο 4.5.1 αντίστοιχα χρησιμοποιείτε το triphone μοντέλο που εκπαιδεύσατε στο βήμα 4.4.5 για να φτιάξετε τα alignments για το DNN-HMM.

Αυτή η διαδικασία εκπαίδευσης είναι κλασικό κομμάτι του ASR και είναι ένα είδος semi-supervised learning.

**Comment by mpektkd** [comment]
Ωραια ευχαριστω πολυ, κολλαγα διοτι σκεφτομουν οτι εφοσον τα triphones εχουν δημιουργηθει με GMM-HMM, δε θα μπορουν να χρησιμοποιηθουν σε DNN. Επισης κατι τελευταιο, θελετε τα alignments να βασιζονται σε triphones απο bigram ή unigram η κι τα δυο?

**Comment by georgepar** [comment]
Το καλύτερο

**Comment by mpektkd** [comment]
Ωραια ευχαριστω πολυ
