### ISSUE TITLE
Παραδοτέα 1ής Προπαρασκευής

### ISSUE THREAD

**Issue by LoniasGR** [slp-ntua/slp-labs#5]
Για την πρώτη προπαρασκευή παραδίδουμε τα script (μαζί με αυτό/αυτά που έχουμε φτιάξει) και την αναφορά; Ή η αναφορά είναι μόνο για το τελικό εργαστήριο;

**Comment by mikatsukons** [comment]
++ Αν παραδώσουμε ένα notebook με markdown αρκεί ως αναφορά ή χρειάζεται κάτι πιο αναλυτικό ;

**Comment by georgepar** [comment]
Στην προπαρασκευή δε ζητάμε αναφορά. Θα γράψετε μια αναφορά σε pdf στην τελική παράδοση του εργαστηρίου.

**Comment by svarnasOikonomou** [comment]
Αν δεν προλαβαινουμε να λυσουμε ολα τα ερωτηματα τι ειναι σημαντικο να υποβαλλουμε στην αναφορα;

**Comment by georgepar** [comment]
Μπορείτε να υποβάλλετε ότι έχετε και ότι δεν έχετε κάνει το δίνετε με το εργαστήριο
