### ISSUE TITLE
[Lab 2] "utt2spk not sorted or has duplicates"

### ISSUE THREAD

**Issue by mikatsukons** [slp-ntua/slp-labs#50]
Μου εμφανίζεται αυτό το error σε πολλά σημεία (είτε ως warning) και δεν καταλαβαίνω τι φταίει. έχω εκτελέσει την σορτ και μετα απο αυτο το utt2spk μου εχει τη μορφη

f1 utterance_id_301
f1 utterance_id_303
f1 utterance_id_304
f1 utterance_id_305
(...)
f5 utterance_id_099
f5 utterance_id_100
f5 utterance_id_102
f5 utterance_id_103
f5 utterance_id_104
f5 utterance_id_105
f5 utterance_id_106
κ.ο.κ

Τι μορφή θα πρέπει να έχουν για να είναι sorted ? τι μπορώ να κάνω για να το φτιάξω

**Comment by georgepar** [comment]
ποιο error?

**Comment by mikatsukons** [comment]
steps/make_mfcc.sh --mfcc-config conf/mfcc.conf --cmd run.pl ./train exp/make_mfcc/train mfcc_train
utils/validate_data_dir.sh: file ./train/utt2spk is not sorted or has duplicates
steps/compute_cmvn_stats.sh data/train exp/make_mfcc/train mfcc
steps/compute_cmvn_stats.sh: no such file data/train/feats.scp
steps/make_mfcc.sh --mfcc-config conf/mfcc.conf --cmd run.pl ./test exp/make_mfcc/test mfcc_test
utils/validate_data_dir.sh: file ./test/utt2spk is not sorted or has duplicates
steps/compute_cmvn_stats.sh data/test exp/make_mfcc/test mfcc
steps/compute_cmvn_stats.sh: no such file data/test/feats.scp
steps/make_mfcc.sh --mfcc-config conf/mfcc.conf --cmd run.pl ./dev exp/make_mfcc/dev mfcc_dev
utils/validate_data_dir.sh: file ./dev/utt2spk is not sorted or has duplicates
steps/compute_cmvn_stats.sh data/dev exp/make_mfcc/dev mfcc
steps/compute_cmvn_stats.sh: no such file data/dev/feats.scp

**Comment by georgepar** [comment]
εχεις κάνει source το `path.sh` πριν το sort;

Κάτω κάτω έχει ένα `export LC_ALL=C` το οποίο αναγκάζει το sorting να γίνεται bytewise, όπως το περιμένει το kaldi.

Λάθος:

```
❯ export LC_ALL=en_US.UTF-8
f1-STE-100 f1
f1-STE-101 f1
f1-STE-102 f1
f1-STE-103 f1
f1-STE-104 f1
f1-STE-105 f1
f1-STE-106 f1
f1-STE-107 f1
f1-STE-108 f1
f1-STE-109 f1
```

Σωστό:

```
❯ export LC_ALL=C
f1-STE-1 f1
f1-STE-10 f1
f1-STE-100 f1
f1-STE-101 f1
f1-STE-102 f1
f1-STE-103 f1
f1-STE-104 f1
f1-STE-105 f1
f1-STE-106 f1
f1-STE-107 f1
```

**Comment by mikatsukons** [comment]
Δηλαδή να κάνω . path.sh
και μετα? sort utt2spk utt2spk?

**Comment by georgepar** [comment]
ναι όποτε ανοίγεις κονσόλα σε project που έχει σχέση με kaldi, το πρώτο που κάνεις πρέπει να είναι `source path.sh`.

Επίσης το δικό σου utt2spk είναι ανάποδα.

**Comment by mikatsukons** [comment]
Επειδή μου ειπατε να αλλάξω τη σειρά των στηλών σε προηγούμενο ισιου τις αλλαξα.
Το έκανα αυτο και το προβλημα παραμένει

**Comment by georgepar** [comment]
Σε προηγούμενο σχόλιο, είχα πει να κάνετε prepend το speaker στα ids (δες το δικό μου comment)....

**Comment by georgepar** [comment]
προφανώς αφού αλλάζουν τα ids, αυτό ισχύει για όλα τα αρχεία (wav.scp, utt2spk, text etc.)

**Comment by mikatsukons** [comment]
Μα τα αρχεία που μας δίνετε εσείς ως test_utterances.txt δεν έχουν αυτό το format. πρεπει αντί για copy να τα γραψουμε στο format που λετε τωρα;

**Comment by georgepar** [comment]
τα αρχεία που σας δίνουμε είναι το official dataset, όπως το δίνουν από το πανεπιστήμιο του USC.

Όπως και να έχει δεν γίνεται η μεταφορά μόνο copy paste και στην προπαρασκευή  φτιάξατε ένα python ή bash script για να σας παράγει τα `wav.scp`, `utt2spk`, `text` αρχεία για κάθε split. Σε αυτό το script αυτό που σας λέω πρέπει να είναι μια - δυο γραμμές αλλαγή.

**Comment by mikatsukons** [comment]
Καταλαβαίνω που λετε να κάνουμε αλλαγή, ναι μισή γραμμή είναι η αλλαγή.
Τα άλλαξα στην μορφή αυτή

wav: f1_utterance_id_001 /content/slp_lab2_data/wav/f1/usctimit_ema_f1_001.wav
utt2spk: f5_utterance_id_168 f5
text: f1_utterance_id_001 This was easy for us.

συνεχίζω να παίρνω το σφάλμα αυτό
steps/make_mfcc.sh --mfcc-config conf/mfcc.conf --cmd run.pl ./train exp/make_mfcc/train mfcc_train
utils/validate_data_dir.sh: Successfully validated data-directory ./train
**steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.**
**run.pl: 4 / 4 failed, log is in exp/make_mfcc/train/make_mfcc_train.*.log**
