### ISSUE TITLE
[Lab2] Monophone Training

### ISSUE THREAD

**Issue by chrisdim** [slp-ntua/slp-labs#51]
Καλημέρα,
Κατά την εκπαίδευση του monophone μοντέλου (αλλά και στη συνέχεια στο allignment και στα triphones) παίρνω το παρακάτω warning, κατά την εκτέλεση του train_mono.sh με παραμέτρους πχ το directory data/train και το λεξικό αντιστοίχισης όλων των λέξεων σε φωνήματα:
WARNING: optional-silence sil is seen only 63.53% of the time at utterance begin. This may not be optimal.
WARNING: optional-silence sil is seen only 10.63% of the time at utterance end. This may not be optimal.
Παρόλα αυτά όλα τα ερωτήματα συνεχίζουν δίχως κάποιο πρόβλημα. Χρειάζεται να λάβω υπόψη το παραπάνω warning ή είναι αναμενόμενο και δεν μας επηρεάζει; Ενδεικτικά αναφέρω %WER 46.25 [ 2855 / 6173, 123 ins, 1273 del, 1459 sub ]  στην περίπτωση αποκωδικοποίησης του dev set με το bigram μοντέλο.
Ευχαριστώ.

**Comment by georgepar** [comment]
Λογικά φαίνονται αυτά. Μπορείτε να αγνοήσετε αυτά τα warning
