### ISSUE TITLE
Πρόβλημα στην εκτέλεση της εντολής extras/instal_mkl.sh

### ISSUE THREAD

**Issue by dkoun** [slp-ntua/slp-labs#55]
Πρόσφατα χρειάστηκε να μεταφερθώ σε ubuntu και κατα την εγκατάσταση των dependencies κατά την εκτέλεση της εντολής extras/instal_mkl.sh εμφανίζεται το παρακάτω μήνυμα , μήπως γνωρίζετε πως διορθώνεται ; 
Fetched 480 kB in 1s (592 kB/s)    
Reading package lists... Done
+ apt-get install -y wget apt-transport-https ca-certificates gnupg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gnupg is already the newest version (2.2.19-3ubuntu2).
gnupg set to manually installed.
wget is already the newest version (1.20.3-1ubuntu1).
wget set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apt-transport-https : Depends: libapt-pkg5.0 (>= 1.3~rc2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
extras/install_mkl.sh: MKL package intel-mkl-64bit-2020.0-088 installation FAILED.

Please open an issue with us at https://github.com/kaldi-asr/kaldi/ if you
believe this is a bug.

**Comment by georgepar** [comment]
Δοκίμασε `sudo apt-get update` και ξανα τρέξτο

**Comment by dkoun** [comment]
δοκίμασα και sudo apt-get update και upgrade αλλά δεν υπήρξε διαφορά. δεν ξέρω αν ευθύνεται το οτι διέγραψα το universe και εβαλα το zesty όπως αναφερόταν στο λινκ που είχατε παραθέσει για την αλλαγή των compilers
