### ISSUE TITLE
[Lab2] Ενδεχόμενο Παράτασης 2ης Εργαστηριακής Άσκησης

### ISSUE THREAD

**Issue by Voul99** [slp-ntua/slp-labs#56]
Καλησπέρα! 
Θα ήθελα να ρωτήσω αν λόγω των εορτών αλλα και της δυσκολίας της άσκησης γίνεται να εξεταστεί το ενδεχόμενο παράτασης της 2ης εργαστηριακής. 
Νομίζω λόγω τόσο της περιόδου των γιορτών αλλα και της δυσκολίας που εμφανίζει η εξ αποστάσεως συνεργασία (και εγκατάσταση και εξοικείωση με το λογισμικό) μπορεί να δοθεί παράταση έστω και λίγων ημερών χωρίς μείωση της βαθμολογίας κατα 20% όπως τις προηγούμενες. 
Ελπίζω το αίτημα να ληφθεί υποψιν. Καλή Χρονία και χαρούμενες γιορτές!

**Comment by ylefen** [comment]
Καλησπέρα, επειδή μεσολάβησε και μια Πρωτοχρονιά και γενικά δεν είχαμε καθόλου τον χρόνο να ξεκουραστούμε δεδομένης της μονιμότητας (σπίτι->υπολογιστής->ύπνος) , γίνεται να δοθούν τουλάχιστον 2-3 μέρες χωρίς ποινή; 

Καλή Χρονιά και Καλές γιορτές

**Comment by dkoun** [comment]
Kαλησπέρα , μια τέτοια βοήθεια θα ήταν όντως πολύ σημαντική αν γινόταν να δοθεί ! Ευχαριστούμε εκ των προτέρων , καλες γιορτές !

**Comment by svarnasOikonomou** [comment]
Καλησπέρα, 
το ενδεχόμενο της παράτασης θα βοηθούσε πάρα πολύ, καθώς αν και η εργασία ειχε βγει πριν απο τις γιορτές έπεσε επάνω σε προόδους και άλλες εργασίες που είχαν deadline μεσα στην εβδομαδά (27/12). Με μια παραταση λιγων ημερων θα μας δοθεί η ευκαιρία να κάνουμε πιο ολοκληρωμένη δουλεια και να μάθουμε καλύτερα το kaldi. 
Ευχαριστούμε εκ των προτέρων! Καλές γιορτές!
