### ISSUE TITLE
[Lab3] - Preprocess

### ISSUE THREAD

**Issue by nox491** [slp-ntua/slp-labs#59]
Δεν μπορώ να δουλέψω με multithreading (μόνο με num_workers=0 λειτουργεί). Το ερρορ βρισκεται παρακάτω. Έχετε καμία ιδεά?

<img width="524" alt="Screenshot 2021-01-12 at 6 39 27 PM" src="https://user-images.githubusercontent.com/57879123/104344395-c435f500-5505-11eb-8eb1-3431ed22c0df.png">

**Comment by pxaris** [comment]
Αν είσαι σε Windows ίσως έχει να κάνει με [αυτό](https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-without-if-clause-protection). Διαφορετικά, βεβαιώσου ότι έχεις την τελευταία version του PyTorch, όπως καθορίζεται στο "lab3/requirements.txt".
