### ISSUE TITLE
BHMA 6

### ISSUE THREAD

**Issue by mpektkd** [slp-ntua/slp-labs#6]
Μια ερωτηση σχετικα με το βημα 6. Η σκεψη μου ειναι η εξης, στην fstcompose θελουμε να γινει η συνθεση VoL (και οχι την LoV), ωστε αν εχουμε εξαρχης τη σωστη λεξη με μια κινηση ε να φυγει απο το L και να παει στην V οπου εκει θα γινει η αποδοχη της με το μικροτερο βαρος, οπου θα ειναι 1 αφου θα χρεωθουμε την κινηση ε. Δευτερον, αν εχουμε λανθασμενη λεξη να μη γινει καποια μεταβαση στην V, αφου θα προσπαθησει με το μικροτερο μονοπατι να τη διορθωσει η L και να την αποδεχτει. 

Κανω καπου λαθος?

Παιζει ρολο η σειρα των συναρτησεων ή ειναι το ιδιο. Θεωρω οτι αν η compose παει κι βαζει κινησεις ε τοτε δεν θα παιζει ρολο η σειρα. Καθως, αν ειχαμε την LoV, τοτε η σωστη λεξη αποδεχεται με ο βαρος και η λαθος με μια κινηση ε διορθωνεται.

 Πως λειτουργει η fstcompose τελικα?

**Comment by georgepar** [comment]
> Μια ερωτηση σχετικα με το βημα 6. Η σκεψη μου ειναι η εξης, στην fstcompose θελουμε να γινει η συνθεση VoL (και οχι την LoV), ωστε αν εχουμε εξαρχης τη σωστη λεξη με μια κινηση ε να φυγει απο το L και να παει στην V οπου εκει θα γινει η αποδοχη της με το μικροτερο βαρος, οπου θα ειναι 1 αφου θα χρεωθουμε την κινηση ε. Δευτερον, αν εχουμε λανθασμενη λεξη να μη γινει καποια μεταβαση στην V, αφου θα προσπαθησει με το μικροτερο μονοπατι να τη διορθωσει η L και να την αποδεχτει.

Εδώ κάνεις λάθος. Αν κάνεις το VoL τότε το V θα αποδέχεται (θα αφήνει να περνάνε) μόνο οι σωστές λέξεις ενώ θα απορρίπτει τις λάθος, οπότε ο L δε θα κάνει τίποτα.

Αν κάνεις το LoV τότε το L θα βρίσκει την ελάχιστη διόρθωση για μια λέξη και το V αποδέχεται μόνο λέξεις στο λεξικό, οπότε τελικά το L θα βρίσκει την ελάχιστη διόρθωση για ένα input ώστε να mapαριστεί σε μια λέξη στο V (το οποίο είναι αυτό που θες). Αν στο LoV δώσεις στην είσοδο λέξη που βρίσκεται μέσα στο λεξικό, τότε η ελάχιστη διόρθωση είναι 0 και το L θα λειτουργεί σαν Identity.

Το compose λειτουργεί όπως η σύνθεση συναρτήσεων που ξέρετε από την ανάλυση, οπότε η σειρά μετράει.

**Comment by andretri** [comment]
Καλησπέρα σας,

Έχω ολοκληρώσει την σύνθεση των L και V (L **o** V), αλλά το αποτέλεσμα που προκύπτει φαίνεται σαν να υπάρχει κάπου λάθος. Πιο συγκεκριμένα, συνθέτοντας τον transducer L με τον V, o γράφος που προκύπτει για τον ορθογράφο S αποτελείται μόνο από μεταβάσεις με input κάποιο χαρακτήρα και output <eps>. 

Μπορείτε να με κατευθείνετε σχετικά με το που μπορεί να βρίσκεται το λάθος;
Για περεταίρω διευκόλυνση, θέλετε να σας επισυνάψω ένα minimal working example (MWE);

**Comment by andretri** [comment]
Kind Reminder...

**Comment by georgepar** [comment]
Καλησπέρα. Δεν μπορώ να προσδιορίσω κάποιο πρόβλημα από αυτή την περιγραφή.

Φαντάζομαι καλείς την fstcompose L.fst V.fst.

Για debugging προτείνω να σχεδιάσεις το L και το V χωριστά με λίγες καταστάσεις και να δεις τη δομή των αυτόματων

Για παραπάνω βοήθεια θέλω κάτι πιο συγκεκριμένο σαν απορία.

**Comment by andretri** [comment]
Τα παρακάτω screenshots αφορούν σε ένα Minimal Working Example για 5 λέξεις από το λεξικό.

Το προιόν της σύνθεσης L, και V είναι αυτό (cropped):
![image](https://user-images.githubusercontent.com/16755652/98570042-a8229700-22bb-11eb-9455-3eb130d8eece.png)

Στο συγκεκριμένο αυτόματο δε γίνονται διορθώσεις, αλλά μόνο διαγραφές, με αποτέλεσμα για μια λέξη (που ανήκει στο V) το output να είναι αυτό:
![image](https://user-images.githubusercontent.com/16755652/98570282-f172e680-22bb-11eb-8101-80962fc6aa49.png)

Κανονικά θα έπρεπε με μια διαφραφή και μια αλλαγή το "avalon" να γίνει "aaron". Έχετε κάποια ιδέα σχετικά με το τι πάει λάθος;

Αν θέλετε, να σας στείλω screenshot (MWE) από τους transducers L και V.

**Comment by georgepar** [comment]
εχετε βάλει το identity transform στον L.fst?

**Comment by andretri** [comment]
Ναι, το identity transform συμπεριλαμβάνεται στον L. Αναλυτικότερα, οι μετασηματισμοί που έχω συμπεριλάβει είναι οι _a:a_, _a:<eps>_, _<eps>:a_ και  _a:b_, όπου a ένα γράμμα της (αγγλικής) αλφαβήτου, a =/= b.

**Comment by georgepar** [comment]
Τότε ακούγεται σωστό. Προτείνω να κάνεις λίγο debug στο L / V χωριστά για να δεις ότι είναι όπως τα περιμένεις, αλλά αυτού του είδους το debugging ξεπερνά τους σκοπούς αυτού του forum.

Closing.
