### ISSUE TITLE
[Lab3] NeAt-Vision not working

### ISSUE THREAD

**Issue by kvilouras** [slp-ntua/slp-labs#64]
Καλησπέρα,

έχω δοκιμάσει να χρησιμοποιήσω το NeAt-Vision για την οπτικοποίηση των attention weights. Δημιουργώ κανονικά 2 json files, ένα για τα δεδομένα και ένα για τα labels όπως περιγράφονται στο readme, αλλά το website δεν δείχνει κάτι (φαίνεται σαν να μην λειτουργεί).

Είναι κάποιο γνωστό bug αυτό ή δεν αναγνωρίζει κάτι από τα json αρχεία που έχω ανεβάσει;

Ευχαριστώ

**Comment by pxaris** [comment]
Καλησπέρα,

Δοκίμασα μόλις και λειτουργεί κανονικά. Χρησιμοποιώ ένα JSON αρχείο (μόνο για τα Data - το mappings των labels δεν είναι απαραίτητο) που έχει το ακόλουθο format (και εμπεριέχει όλα τα samples):

```
[
    {
        "text": [
            "affable",
            "if",
            "not",
            "timeless",
            ",",
            "like",
            "mike",
            "raises",
            "some",
            "worthwhile",
            "themes",
            "while",
            "delivering",
            "a",
            "wholesome",
            "fantasy",
            "for",
            "kids",
            "."
        ],
        "label": 0,
        "prediction": 0,
        "attention": [
            0.054727911949157715,
            0.050882842391729355,
            0.038399554789066315,
            0.04712891951203346,
            0.04059050232172012,
            0.04217269644141197,
            0.0328814759850502,
            0.03526868671178818,
            0.0338919460773468,
            0.05338773503899574,
            0.0486895814538002,
            0.04062413051724434,
            0.058526262640953064,
            0.05030245706439018,
            0.07825610786676407,
            0.08630755543708801,
            0.07752958685159683,
            0.07454473525285721,
            0.05588730052113533
        ],
        "id": "sample_0"
    }
]
```

Μπορείς να σώσεις το παραπάνω σε ένα "test.json" και να το ανεβάσεις ως "Data file" στο [site του Neat Vision](https://cbaziotis.github.io/neat-vision/) για να το δεις ότι λειτουργεί.

**Comment by kvilouras** [comment]
Τελικά είχα λάθος το data.json
Πρέπει να προκύψει μια λίστα από dictionaries (ένα για κάθε sample), ενώ εγώ δημιουργούσα 1 dictionary, όπου κάθε key περιείχε ένα list of lists.
