### ISSUE TITLE
[Lab 3]: Ερώτημα 6 - Αναπαράσταση με BoW

### ISSUE THREAD

**Issue by pmisiakos** [slp-ntua/slp-labs#65]
Καλησπέρα σας, 

Ήθελα να κάνω μία ερώτηση σχετικά με την αναπαράσταση με Bag Of Words. 

Δεν έχω καταλάβει πως το νευρωνικό θα εκπαιδεύεται στα BoW χαρακτηριστικά. Αυτό εκ πρώτης όψεος φαίνεται αρκετά ασύμβατο με τα embeddings, αφού τα embeddings χρειάζονται το μετασχηματισμένο word 2 index σύνολο δεδομένων, ενώ τα tfidf χρειάζονται το αρχικό corpus. 

Μήπως θα μπορούσατε να εξηγήσετε παραπάνω πώς αναμένεται να χρησιμοποιηθούν τα BoW?

Με εκτίμηση, 
Παναγιώτης Μισιακός.

**Comment by pxaris** [comment]
Καλησπέρα,

Όπως σωστά λες, τα BoW / TD-IDF vectors (για κάθε πρόταση) προκύπτουν κατευθείαν από το corpus και δεν εμπίπτουν σε κάποια μάθηση σχετική με το νευρωνικό που χρησιμοποιούμε εδώ.

Αυτό που θέλουμε είναι να χρησιμοποιήσουμε τα vectors αυτά (BoW / TD-IDF) ώστε να εμπλουτίσουμε τις αναπαραστάσεις που προέρχονται από την ακολουθία των embeddings.

Για παράδειγμα, αν εξάγουμε τα TD-IDF βάρη των λέξεων μιας πρότασης, ξέρουμε ότι αυτά κωδικοποιούν τη βαρύτητα που έχει κάθε λέξη στο συγκεκριμένο κείμενο. Πώς θα ήταν λογικό να χρησιμοποιήσουμε αυτό το "βάρος" κάθε λέξης, έχοντας την ακολουθία των embeddings που προκύπτει από το embedding layer του νευρωνικού;

Ως προς την υλοποίηση, θα πρέπει τα χαρακτηριστικά αυτά (BoW / TD-IDF) να δίνονται στη `forward` του νευρωνικού και αυτό να τα χρησιμοποιεί με κάποιον τρόπο που εσείς θα επιλέξετε. Άρα, αναμένεται η εξαγωγή των παραπάνω χαρακτηριστικών να γίνεται στη `SentenceDataset` (συγκεκριμένα στην `__init__`) και να συνενώνονται με κάποιο τρόπο στο `example` της `__getitem__`.

**Comment by pmisiakos** [comment]
Κατάλαβα, ευχαριστώ πολύ!!
