### ISSUE TITLE
[Lab3 - 6.1] Tf-Idf Vectorizer returns None

### ISSUE THREAD

**Issue by chrisdim** [slp-ntua/slp-labs#67]
Καλησπέρα,
Θα ήθελα να ρωτήσω πώς ακριβώς διαχειριζόμαστε τις περιπτώσεις στις οποίες ο tf-idf vectorizer της sklearn επιστρέφει None για κάποιες λέξεις του corpus, οι οποίες όμως εμφανίζονται εντός αυτού (πιο συγκεκριμένα μου έτυχε στo άρθρο 'a'), με αποτέλεσμα να μην επιτρέπεται στη συνέχεια πράξη με ακέραιο αριθμό.

Επιπλέον, θα ήθελα να ρωτήσω αν μπορούμε να υποβάλλουμε και κάποιες διορθώσεις στο κομμάτι της προπαρασκευής μαζί με την τελική υποβολή του 3ου εργαστηρίου.

Ευχαριστώ

**Comment by pxaris** [comment]
Καλημέρα,

Δεν αναμένεται η `TfidfVectorizer` να γυρνάει `None`. Δες ξανά τα ορίσματά της καθώς και πως μεταχειρίζεσαι το `max_sentence_length` όταν φτιάχνεις την λίστα από τα ΤF-IDF βάρη που περνάς στη forward, μήπως υπάρχει εκεί κάποιο bug.

Επίσης, ναι μπορείτε να κάνετε διορθώσεις στο κομμάτι της Προπαρασκευής.

**Comment by chrisdim** [comment]
Ευχαριστώ, το πρόβλημα ήταν ότι ο tokenizer της Tfidfvectorizer έκανε πιο επιθετικό preprocessing και πέταγε τις λέξεις που αποτελούνταν από έναν χαρακτήρα μόνο. Το αναφέρω σε περίπτωση που αντιμετωπίσει κάποιος άλλος παρόμοιο πρόβλημα.
