### ISSUE TITLE
Lab3-3.2

### ISSUE THREAD

**Issue by mpektkd** [slp-ntua/slp-labs#68]
Καλησπερα, θα ηθελα να κανω μια ερωτηση σχετικα με το attention layer. Στο ερωτημα 3, οι τυποι (10), (13) δινουν τα αi, αλλα δεν μπορω να εντοπισω στον κωδικα που μας δινεται στο github, σε ποιο σημειο υπολογιζονται με αυτους τους τυπους. Μου φαινεται οτι παιρνει κανονικη κατανομη, για τα ai. Εμεις καλουμαστε να αλλαξουμε τον κωδικα η μπορουμε να τον χρησιμοποιησουμε αυτουσιο?

Και αν τον χρησιμοποιησουμε αυτουσιο, πως ακριβως θα γινει αυτο. Θελω να πω, με βαση αυτους τους τυπους:
![image](https://user-images.githubusercontent.com/62422421/109226319-38331080-77c7-11eb-9ea2-eaea7083249d.png)

πρεπει να εξαγουμε τα ui και υστερα να εφαρμοσουμε attention, το οποιο αν ακολουθησουμε το δοσμενο κωδικα δεν βλεπω πως θα γινει. Διορθωστε με αν κανω καποιο λαθος.

**Comment by mpektkd** [comment]
Το παρατηρησα λιγο καλυτερα, και νομιζω, καταλαβα το λαθος στη σκεψη μου. Οποτε ολα καλα.

**Comment by georgepar** [comment]
Δεν είναι ακριβώς αυτούσιο, γιατί έχει κάποια optimizations στην υλοποίηση. Σου βάζω τις σχετικές γραμμές:

- Create attention weights u_i by projecting e_i (Batch size, Length, Dimension) to (Batch size, Length) 
![image](https://user-images.githubusercontent.com/5895309/109227611-42eea500-77c9-11eb-8138-e0a394ba5408.png)

```python
scores = self.non_linearity(inputs.matmul(self.attention_weights))
```

- Create attention scores a_i (Batch size, Length) by converting u_i to a probability distribution using softmax

![image](https://user-images.githubusercontent.com/5895309/109227572-32d6c580-77c9-11eb-941c-e5a69c1fe712.png)

```python
scores = self.softmax(scores)
```

- Reweight representations at each timestep e_i using attention scores a_i by taking the weighted sum

![image](https://user-images.githubusercontent.com/5895309/109227642-4f72fd80-77c9-11eb-93fa-1c8143934cef.png)

```python
# multiply each hidden state with the attention weights
weighted = torch.mul(inputs, scores.unsqueeze(-1).expand_as(inputs))

# sum the hidden states
representations = weighted.sum(1).squeeze()
```

Αυτό που σε μπερδεύει λογικά είναι αυτές οι γραμμές:

```python
# construct a mask, based on the sentence lengths
mask = self.get_mask(scores, lengths)

# apply the mask - zero out masked timesteps
masked_scores = scores * mask

# re-normalize the masked scores
_sums = masked_scores.sum(-1, keepdim=True)  # sums per row
scores = masked_scores.div(_sums)  # divide by row sum
```

Εδώ μασκάρει τα padded timesteps για να μην τα συμπεριλάβει στον υπολογισμό των attention scores (δε θες να κάνεις attend στο padding).
Tο renormalization συμβαίνει ώστε τα `a_i` να συνεχίζουν να αθροίζουν στη μονάδα.

Γκαουσιανή δεν υπάρχει ούτε στις εξισώσεις ούτε στον κώδικα. Softmax είναι

**Comment by mpektkd** [comment]
Μαλιστα, τωρα τα ξεδιαλυνα ακομα περισσοτερο, ευχαριστω πολυ.

**Comment by mpektkd** [comment]
Αλλη μια ερωτηση σχετικα με τα μοντελα, που χρησιμοποιουμε LSTM. Στο ερωτημα 2 αναφερεται να παραλειψουμε τη μη-γραμμικοτητα. Αυτο, ισχυει και σε ολα τα αλλα ερωτηματα που κανουμε χρηση LSTM ή μπορουμε να δοκιμασουμε και με προσθηκη μη γραμμικοτητας? Δεν εννοω τη μη γραμμικοτηα του attention, εννοω τη μηγραμμικοτητα οπως ειχαμε βαλει στο hidden layer στην προπαρασκευη.

**Comment by pxaris** [comment]
1) Μπορείτε να παραλείψετε τη μη-γραμμικότητα σε όλα τα LSTM μοντέλα ή να δοκιμάσετε να τη συμπεριλάβετε, ό,τι θέλετε. Απλά, σημειώστε τις επιλογές / δοκιμές που κάνατε στην αναφορά. 

2) Χρησιμοποιώντας τη μέθοδο `pack_padded_sequence` (περνώντας τα `lengths` και ορίζοντας ότι η πρώτη διάσταση αναφέρεται στο batch μέσω του boolean `batch_first=True`) πριν τροφοδοτήσεις το LSTM και την `pad_packed_sequence` μετά, καταλήγεις με το shape του `h_t` να είναι `batch_size` x `max_length (in batch)` x `hidden_dim`. 
Άρα, στο παράδειγμα που δίνεις, καταλαβαίνω ότι έχεις ορίσει `hidden size` του LSTM `50` (hidden_dim), `batch size` `128` και `max sequence length` επίσης `50`. Αυτό που συνέβη είναι ότι στο συγκεκριμένο batch το πραγματικό (μη padded) max length ήταν `48` και αρά το `h_t.shape` που βλέπεις είναι `[128, 48, 50]`.   
(Εννοείται πως είναι αδύνατο να πάρεις length του output μεγαλύτερο από την αρχική ακολουθία.)

**Comment by mpektkd** [comment]
Μαλιστα, απολυτα κατανοητο, ευχαριστω πολυ.
