### ISSUE TITLE
Ώρα Παράδοσης Προπαρασκευής 

### ISSUE THREAD

**Issue by ylefen** [slp-ntua/slp-labs#7]
Καλησπέρα. Εγώ και κάποιοι συμφοιτητές μου είχαμε την εντύπωση ότι η παράδοση της προπαρασκευής είναι μέχρι Δευτέρα βράδυ (1 βδομάδα ακριβώς). Ωστόσο, στο moodle βγάζει <24 ώρες στο Time Remaining, δηλαδή Κυριακή βράδυ. Τι ισχύει;

**Comment by georgepar** [comment]
![screenshot](https://user-images.githubusercontent.com/5895309/97800032-6ac66580-1c3a-11eb-9b63-950c40cc286d.JPG)
