### ISSUE TITLE
Lab3-2.1

### ISSUE THREAD

**Issue by Alphecca-kj** [slp-ntua/slp-labs#71]
Καλησπερα, κατα την υλοποίηση του 2ου ερωτηματος με την LSTM μου πεταει συνεχως αυτο το error και δεν ξερω πως να το φτιαξω : ValueError: Expected input batch_size (384) to match target batch_size (128) . 
Έχετε καποια ιδεα τι μπορει να φταιει;

**Comment by pxaris** [comment]
Καλημέρα, δες στη σελίδα 10 της [βοηθητικής παρουσίασης](https://drive.google.com/file/d/1brMcP5PvdSx19vqgtG-vq-8ItD-2Aeqt/view?usp=sharing) μια ενδεκτική υλοποίηση της forward του LSTM που πιθανόν να σε βοηθήσει.

**Comment by svarnasOikonomou** [comment]
Καλημερα, ευχαριστω για την απαντηση, το δοκισα και βγαζει το ιδιο error και μαλιστα όταν έκανε κάποιες αλλαγές στον κώδικα για να φτιάξει (τα είχα περάσει απο linear layer και μετα τα εκανα ολα concartenate) μου εβγαζε ενα αντιστοιχο error (5x) : 
ValueError: Expected input batch_size (384) to match target batch_size (128)

**Comment by pxaris** [comment]
Προφανώς, υπάρχει κάποιο bug στους μετασχηματισμούς που περνάνε τα δεδομένα. Θα πρέπει να κάνεις debugging εστιάζοντας στο πως αλλάζει το `shape` σε κάθε βήμα για να το εντοπίσεις.
