### ISSUE TITLE
Πακετα και εκδοσεις python

### ISSUE THREAD

**Issue by iliaskoum** [slp-ntua/slp-labs#73]
Καλημέρα, 

θα μπορούσατε να μας πείτε ποια πακέτα της python να κατεβάσουμε (και ποιες εκδόσεις) για να μην έχουμε προβλήματα;

Σας ευχαριστώ

**Comment by efthymisgeo** [comment]
Μπαινεις εδω που λεει η εκφωνηση https://github.com/slp-ntua/slp-labs/tree/master/lab1 και ειναι το requirements.txt

Προσωπικα προτεινω να στησετε το miniconda στο μηχανημα σας και να φτιαξετε εκει ενα environment για τo lab. Αλλα οπως σας βολεψει
