### ISSUE TITLE
Lab 1 - Step 5

### ISSUE THREAD

**Issue by artpyl** [slp-ntua/slp-labs#76]
Καλησπέρα, θα ήθελα να κάνω μια ερώτηση:

Στο βήμα 5α φτιάχνουμε ένα unoptimized fst το οποίο στο ερώτημα 5β θέλουμε να μετατρέψουμε σε (optimized) V.fst και στο 5γ να το κάνουμε compile. Όμως, για να φτιάξουμε το unoptimized fst έχουμε κάνει ήδη κάποια compile (επίσης θεωρήσαμε ότι οι συναρτήσεις του 5β παίρνουν ως είσοδο compiled fsts). Έτσι δεν μπορεί να εκτελεστεί το compile του 5γ. Υπάρχει κάποιο λάθος σε αυτό που περιέγραψα?

**Comment by dimsot17** [comment]
Σωστή είναι η διαδικασία που περιγράψατε, κάποια επιμέρους βήματα είναι ενιαία και η σειρά που περιγράφονται δεν είναι αυστηρή.

**Comment by efthymisgeo** [comment]
Να προσθεσω πως η διατυπωση μας ειναι κακή έχετε απόλυτο δικιο. Αυτό που θέλουμε είναι να το compile και το optimization

**Comment by artpyl** [comment]
Σας ευχαριστώ πολύ για την διευκρίνηση!
