### ISSUE TITLE
Bήμα 7

### ISSUE THREAD

**Issue by SnifflePiffle** [slp-ntua/slp-labs#77]
Καλησπέρα, στο βήμα 7 έχουμε κάνει compose τα δύο FSTs (LoV), αλλά όταν δοκιμάζουμε το script predict.sh (έχουμε κάνει τις απαραίτητες διορθώσεις όσον αφορά τα directories κτλ) στο S.fst, δεν παράγεται κάποιο αποτέλεσμα. Γιατί μπορεί να συμβαίνει αυτό;

**Comment by eleannavali** [comment]
Τσεκρετε αν στον μετατροπεα L εχετε βαλει  τελικη κατασταση (την 0 λογικα). Αυτο επαιξε σε εμας.
