### ISSUE TITLE
Απορίες για 1η σειρά ασκήσεων

### ISSUE THREAD

**Issue by Georgios-Milis** [slp-ntua/slp-labs#79]
Καλησπέρα, θα ήθελα να ρωτήσω τα εξής:

1) Αν έχουμε ισοπαλία σε κόστη μετατροπής από τον Levenshtein transducer, επιλέγουμε αυθαίρετα κάποια ή υπάρχει προτίμηση;

2) Το back-off που ζητείται στην άσκηση 5 θέλετε να είναι με smoothing ή απλό "stupid" back-off;

Ευχαριστώ πολύ εκ των προτέρων.

**Comment by dimsot17** [comment]
Καλησπέρα, στο (1) μπορείτε να επιλέξεται αυθαίρετα σε περίπτωση ισοπαλίας και στο (2) χρησιμοποιήστε απλό back-off.
