### ISSUE TITLE
Μη έγκυρος χαρακτήρας

### ISSUE THREAD

**Issue by kostasang** [slp-ntua/slp-labs#8]
Καλησπέρα, στο αρχείο wiki.txt υπάρχει το ζεύγος λέξεων gauarana guaraná. Αφενός ο χαρακτήρας á δεν υπάρχει στο δικό μας αρχείο chars.syms και αφετέρου η βοηθητική συνάρτηση run_cmd δεν μπορεί να διαχειριστεί τον εν λόγω χαρακτήρα πετώντας error UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 28: invalid continuation byte. Φαντάζομαι μπορούμε να παραβλέψουμε το συγκεκριμένο ζεύγος και οποιοδήποτε άλλο δημιουργεί αντίστοιχο πρόβλημα;

** Το ίδιο συμβαίνει και με το ζεύγος ninties	1990s

**Comment by georgepar** [comment]
Ναι μπορείτε να τα σκιπαρετε

**Comment by DimLiak** [comment]
Το ίδιο συμβαίνει και για το ζεύγος "aka a.k.a"

**Comment by georgepar** [comment]
same
