### ISSUE TITLE
Απορία για 1η σειρά γραπτών ασκήσεων, άσκηση 5

### ISSUE THREAD

**Issue by nikpag** [slp-ntua/slp-labs#80]
Χαίρετε, 

θα ήθελα να ρωτήσω σχετικά με την άσκηση 5, αν οι προτάσεις που μας δίνονται θεωρούμε ότι εμφανίζονται η μία μετά την άλλη "κολλητά". Για παράδειγμα, στην περίπτωση της πρότασης "lovely mother lovely grandmother lovely", θεωρούμε ότι έχουμε:

lovely mother lovely grandmother lovely
lovely mother lovely grandmother lovely
lovely mother lovely grandmother lovely
lovely mother lovely grandmother lovely
lovely mother lovely grandmother lovely
lovely mother lovely grandmother lovely
lovely mother lovely grandmother lovely

οπότε το "lovely lovely" εμφανίζεται 6 φορές σε αυτές τις 7 προτάσεις, ή θεωρούμε ότι δεν εμφανίζεται καμία φορά;

Σας ευχαριστώ,

**Comment by dimsot17** [comment]
Ναι, θεωρούμε ότι εμφανίζεται 6 φορές.
