### ISSUE TITLE
Lab2. Πρόβλημα στην εντολή make

### ISSUE THREAD

**Issue by ThodorisMathimatikos** [slp-ntua/slp-labs#81]
Καλησπέρα,

προσπαθώντας να ακολουθήσω τα βήματα του εργαστηρίου δεν έφτασα μακριά. Συγκεκριμένα στον φάκελο tools του kaldi και αφού κατεβάσω όλα τα dependencies και βάζοντας τις σωστές εκδόσεις των gcc, g++, gfortran, πάω να τρέξω την make και μου σκάει το vm. Είναι ubuntu 20.04 με 6 CPUs και 6,6GB μνήμη. Δοκιμάζοντας με διάφορους αριθμούς CPUs στην make παρατηρώ ότι όλοι σκάνε στο ίδιο σημείο, το οποίο παραθέτω στο παρακάτω snip. Επίσης έχω και τα τελευταία logs της μηχανής. 

Συνάντησε κάποιος άλλος/άλλη το ίδιο πρόβλημα;
![crack](https://user-images.githubusercontent.com/93331651/167213382-a1efb593-1d24-47cf-b1ab-54f8589d4671.png)
![logs](https://user-images.githubusercontent.com/93331651/167213386-b2525b24-332c-4e65-96fc-145fe6c9b5e1.png)

**Comment by georgepar** [comment]
Μάλλον σκάει λόγω μνήμης. εγκαταστήστε το htop και ανοιξτε το σε μια κονσόλα ενώ κάνει compile για επιβεβαίωση. 

Αν είναι αυτό το πρόβλημα προτείνω make -j1 για να ελαχιστοποιηθεί το memory usage και αν και αυτό δεν δουλεύει τότε ενα μεγαλύτερο vm / dual boot

**Comment by ThodorisMathimatikos** [comment]
Όντως, με make -j1 τα κατάφερε και έτρεξε. Ευχαριστώ πάρα πολύ.
