### ISSUE TITLE
Lab2 - Βήμα#5 - TorchSpeechDataset

### ISSUE THREAD

**Issue by GiannisPikoulis** [slp-ntua/slp-labs#84]
Καλησπέρα σας. Έχω εκτελέσει τα υποβήματα 1,2 του βήματος 5 και προσπαθώ να διαβάσω τα δεδομένα train/dev/test με χρηση της κλάσης TorchSpeechDataset που μας δίνετε. Αν και πιστεύω ότι έχω δώσει τα σωστά ορίσματα στα recipe_dir, dset, ali_dir, μου πετάει σφάλμα "UnsupportedOperation: fileno" το οποίο δεν είναι και πολύ διαφωτιστικό. Φοβάμαι μήπως δεν έχω κάνει κάτι σωστά με τα paths κατά το setup του kaldi_io. Επίσης είναι απαραίτητο να τρέχουμε το kaldi_io σε περιβάλλον python 2.7?

**Comment by georgepar** [comment]
1. Σε περίπτωση που τρέχετε το σκριπτ μέσω κάποιου ide, νομίζω πρέπει να τρέξει από κονσόλα σύμφωνα με αυτό https://stackoverflow.com/questions/31080829/python-error-io-unsupportedoperation-fileno/31081957#31081957
2. Πρέπει να δουλεύει και σε python 3 αλλά δε θυμάμαι αν έχουν ενημερωθεί όλα τα σκριπτ. Έχω την εντύπωση ότι αν το δοκιμάσετε θα παίξει.

**Comment by GiannisPikoulis** [comment]
Όλα κομπλέ τώρα, τρέχει κανονικά. Ευχαριστώ. Κλείνω το issue.
