### ISSUE TITLE
Lab 2 - Εγκατάσταση

### ISSUE THREAD

**Issue by AndrewManiatis** [slp-ntua/slp-labs#86]
Κάθε φορά που κάνω make εδώ αφού όλα τα dependencies είναι οκ

![image](https://user-images.githubusercontent.com/44208147/168095856-07a13d65-e2cf-4cec-9194-3acc7cb93eb4.png)

το virtual box στο οποίο έχω Ubuntu κρασάρει. Γενικά έχω διαθέσιμο χώρο. Τι μπορεί να φταίει;

**Comment by georgepar** [comment]
Μάλλον μενει από μνήμη. Δείτε εδώ
https://github.com/slp-ntua/slp-labs/issues/81

**Comment by AndrewManiatis** [comment]
Ευχαριστώ λύθηκε.
