### ISSUE TITLE
[Lab 2] 4.5.3

### ISSUE THREAD

**Issue by timtsapras23** [slp-ntua/slp-labs#91]
Καλησπέρα, 
Οταν προσπαθώ να τρέξω την TorchDataset (προσπάθησα και απο Jupyter Notebook) μου βγάζει μόνιμα errors. Θα έπρεπε να βάλω κάτι στο path από το Kaldi_io?

**Comment by georgepar** [comment]
Τι errors βγάζει?

**Comment by timtsapras23** [comment]
![errors](https://user-images.githubusercontent.com/58435729/169302650-5a0a42f8-c211-4dc5-b5ca-b755eefb548f.png)

**Comment by timtsapras23** [comment]
![errors2](https://user-images.githubusercontent.com/58435729/169303491-841a1faf-b84c-43d6-8fce-6247ae527023.png)
Βγάζει κι αυτό όποτε έτρεχα την run_dnn.sh

**Comment by georgepar** [comment]
Έχεισ κάνει source το path.sh? Φαίνεται σαν να μην βρίσκει το kaldi
